"use strict";

$.$setTemplate( "gsui-patterns-pattern", () =>
	$.$div( { class: "gsuiPatterns-pattern" },
		$.$div( { class: "gsuiPatterns-pattern-grip" },
			$.$icon( { icon: "grip-v" } ),
		),
		$.$div( { class: "gsuiPatterns-pattern-head" },
			$.$div( { class: "gsuiPatterns-pattern-info" },
				$.$button( { class: "gsuiPatterns-pattern-btn gsuiPatterns-pattern-btnInfo", "data-action": "editInfo", "data-tooltip": GSTX.$patterns_editPatternInfo },
					$.$icon( { icon: "question" } ),
				),
				$.$div( { class: "gsuiPatterns-pattern-name" } ),
				$.$button( { class: "gsuiPatterns-btnSolid gsuiPatterns-pattern-dest", "data-action": "redirect", "data-tooltip": GSTX.$patterns_redirectPattern },
					$.$icon( { class: "gsuiPatterns-btnIcon", icon: "mixer" } ),
					$.$span( { class: "gsuiPatterns-btnText" } ),
				),
			),
			$.$button( { class: "gsuiPatterns-pattern-btn", "data-action": "clone", "data-tooltip": GSTX.$patterns_clonePattern },
				$.$icon( { icon: "clone" } ),
			),
			$.$button( { class: "gsuiPatterns-pattern-btn", "data-action": "remove", "data-tooltip": GSTX.$patterns_deletePattern },
				$.$icon( { icon: "close" } ),
			),
		),
		$.$div( { class: "gsuiPatterns-pattern-content" } ),
		$.$div( { class: "gsuiPatterns-pattern-placeholder" },
			$.$icon( { icon: "file-corrupt" } ),
		),
	)
);
