"use strict";

GSUsetTemplate( "gsui-patterns-infoPopup", () =>
	GSUcreateDiv( { id: "gsuiPatterns-infoPopupContent" },
		GSUcreateElement( "fieldset", null,
			GSUcreateElement( "legend", null, "Type" ),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "radio", name: "type", value: "drum" } ),
				GSUcreateIcon( { icon: "buf-drum" } ),
				GSUcreateSpan( { inert: true }, "drum" ),
			),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "radio", name: "type", value: "fx" } ),
				GSUcreateIcon( { icon: "buf-fx" } ),
				GSUcreateSpan( { inert: true }, "fx" ),
			),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "radio", name: "type", value: "vocal" } ),
				GSUcreateIcon( { icon: "buf-vocal" } ),
				GSUcreateSpan( { inert: true }, "vocal" ),
			),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "radio", name: "type", value: "loop" } ),
				GSUcreateIcon( { icon: "buf-loop" } ),
				GSUcreateSpan( { inert: true }, "loop" ),
				GSUcreateSpan( { inert: true }, "bpm" ),
				GSUcreateInput( { class: "gsuiPopup-inputText", type: "number", name: "bpm", min: 1, max: 999.99, step: .01 } ),
			),
		),
		GSUcreateElement( "fieldset", null,
			GSUcreateElement( "legend", null, "Edit" ),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "checkbox", name: "reverse" } ),
				GSUcreateIcon( { icon: "reverse" } ),
				GSUcreateSpan( { inert: true }, "reverse" ),
			),
		),
		GSUcreateElement( "fieldset", null,
			GSUcreateElement( "legend", null, "Name" ),
			GSUcreateLabel( null,
				GSUcreateInput( { class: "gsuiPopup-inputText", type: "text", name: "name" } ),
			),
		),
	)
);
