"use strict";

GSUsetTemplate( "gsui-patterns-infoPopup", () =>
	GSUcreateDiv( { id: "gsuiPatterns-infoPopupContent" },
		GSUcreateElement( "fieldset", null,
			GSUcreateElement( "legend", null, "Type" ),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "radio", name: "type", value: "drum" } ),
				GSUcreateI( { class: "gsuiIcon", "data-icon": "buf-drum" } ),
				GSUcreateSpan( null, "drum" ),
			),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "radio", name: "type", value: "fx" } ),
				GSUcreateI( { class: "gsuiIcon", "data-icon": "buf-fx" } ),
				GSUcreateSpan( null, "fx" ),
			),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "radio", name: "type", value: "vocal" } ),
				GSUcreateI( { class: "gsuiIcon", "data-icon": "buf-vocal" } ),
				GSUcreateSpan( null, "vocal" ),
			),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "radio", name: "type", value: "loop" } ),
				GSUcreateI( { class: "gsuiIcon", "data-icon": "buf-loop" } ),
				GSUcreateSpan( null, "loop" ),
				GSUcreateSpan( null, "bpm" ),
				GSUcreateInput( { class: "gsuiPopup-inputText", type: "number", name: "bpm", min: 1, max: 999.99, step: .01 } ),
			),
		),
		GSUcreateElement( "fieldset", null,
			GSUcreateElement( "legend", null, "Edit" ),
			GSUcreateLabel( null,
				GSUcreateInput( { type: "checkbox", name: "reverse" } ),
				GSUcreateI( { class: "gsuiIcon", "data-icon": "reverse" } ),
				GSUcreateSpan( null, "reverse" ),
			),
		),
		GSUcreateElement( "fieldset", null,
			GSUcreateElement( "legend", null, "Name" ),
			GSUcreateLabel( null,
				GSUcreateInput( { class: "gsuiPopup-inputText", type: "text", name: "name" } ),
			),
		),
	)
);
