"use strict";

$.$setTemplate( "gsui-patterns-infoPopup", () =>
	$.$div( { id: "gsuiPatterns-infoPopupContent" },
		$.$elem( "fieldset", null,
			$.$elem( "legend", null, "Type" ),
			$.$label( null,
				$.$input( { type: "radio", name: "type", value: "drum" } ),
				$.$icon( { icon: "buf-drum" } ),
				$.$span( { inert: true }, "drum" ),
			),
			$.$label( null,
				$.$input( { type: "radio", name: "type", value: "fx" } ),
				$.$icon( { icon: "buf-fx" } ),
				$.$span( { inert: true }, "fx" ),
			),
			$.$label( null,
				$.$input( { type: "radio", name: "type", value: "vocal" } ),
				$.$icon( { icon: "buf-vocal" } ),
				$.$span( { inert: true }, "vocal" ),
			),
			$.$label( null,
				$.$input( { type: "radio", name: "type", value: "loop" } ),
				$.$icon( { icon: "buf-loop" } ),
				$.$span( { inert: true }, "loop" ),
				$.$span( { inert: true }, "bpm" ),
				$.$input( { class: "gsuiPopup-inputText", type: "number", name: "bpm", min: 1, max: 999.99, step: .01 } ),
			),
		),
		$.$elem( "fieldset", null,
			$.$elem( "legend", null, "Edit" ),
			$.$label( null,
				$.$input( { type: "checkbox", name: "reverse" } ),
				$.$icon( { icon: "reverse" } ),
				$.$span( { inert: true }, "reverse" ),
			),
		),
		$.$elem( "fieldset", null,
			$.$elem( "legend", null, "Name" ),
			$.$label( null,
				$.$input( { class: "gsuiPopup-inputText", type: "text", name: "name" } ),
			),
		),
	)
);
