"use strict";

GSUI.setTemplate( "gsui-patterns", () => [
	GSUI.createElement( "div", { class: "gsuiPatterns-panel gsuiPatterns-panelBuffers" },
		GSUI.createElement( "div", { class: "gsuiPatterns-panel-menu" },
			GSUI.createElement( "i", { class: "gsuiPatterns-panel-icon gsuiIcon", "data-icon": "waveform" } ),
			GSUI.createElement( "span", { class: "gsuiPatterns-panel-title" }, "samples" ),
		),
		GSUI.createElement( "div", { class: "gsuiPatterns-placeholderToCheck gsuiPatterns-panel-list" } ),
		GSUI.createElement( "div", { class: "gsuiPatterns-placeholder" },
			GSUI.createElement( "span", null, "drag 'n drop raw files here (mp3, ogg, wav)" ),
		),
	),
	GSUI.createElement( "div", { class: "gsuiPatterns-panel gsuiPatterns-panelDrums" },
		GSUI.createElement( "div", { class: "gsuiPatterns-panel-menu" },
			GSUI.createElement( "i", { class: "gsuiPatterns-panel-icon gsuiIcon", "data-icon": "drums" } ),
			GSUI.createElement( "span", { class: "gsuiPatterns-panel-title" }, "drums" ),
			GSUI.createElement( "button", { class: "gsuiPatterns-btnSolid", "data-action": "newDrums", title: "Create a new drums pattern" },
				GSUI.createElement( "i", { class: "gsuiPatterns-btnIcon gsuiIcon", "data-icon": "plus" } ),
				GSUI.createElement( "span", { class: "gsuiPatterns-btnText" }, "new drums" ),
			),
		),
		GSUI.createElement( "div", { class: "gsuiPatterns-placeholderToCheck gsuiPatterns-panel-list" } ),
		GSUI.createElement( "div", { class: "gsuiPatterns-placeholder" },
			GSUI.createElement( "span", null, "no drums yet" ),
		),
	),
	GSUI.createElement( "div", { class: "gsuiPatterns-panel gsuiPatterns-panelKeys" },
		GSUI.createElement( "div", { class: "gsuiPatterns-panel-menu" },
			GSUI.createElement( "i", { class: "gsuiPatterns-panel-icon gsuiIcon", "data-icon": "oscillator" } ),
			GSUI.createElement( "span", { class: "gsuiPatterns-panel-title" }, "keys" ),
			GSUI.createElement( "button", { class: "gsuiPatterns-btnSolid", "data-action": "newSynth", title: "Create a new synthesizer" },
				GSUI.createElement( "i", { class: "gsuiPatterns-btnIcon gsuiIcon", "data-icon": "plus" } ),
				GSUI.createElement( "span", { class: "gsuiPatterns-btnText" }, "new synth" ),
			),
		),
		GSUI.createElement( "div", { class: "gsuiPatterns-placeholderToCheck gsuiPatterns-panel-list" } ),
		GSUI.createElement( "div", { class: "gsuiPatterns-placeholder" },
			GSUI.createElement( "span", null, "no synth yet" ),
		),
	),
] );
