"use strict";

$.$setTemplate( "gsui-fx-delay", () => [
	$.$elem( "gsui-effect-param-row", { "data-prop": "time" },
		$.$elem( "gs-label", null, "time" ),
		$.$elem( "gs-output" ),
		$.$elem( "gsui-slider", { type: "linear-x", step: .01, min: 0, max: 2, "mousemove-size": 1600 } ),
	),
	$.$elem( "gsui-effect-param-row", { "data-prop": "gain" },
		$.$elem( "gs-label", null, "gain" ),
		$.$elem( "gs-output" ),
		$.$elem( "gsui-slider", { type: "linear-x", step: .01, min: 0, max: .95, "mousemove-size": 1600 } ),
	),
	$.$elem( "gsui-effect-param-row", { "data-prop": "pan" },
		$.$elem( "gs-label", null, "pan" ),
		$.$elem( "gs-output" ),
		$.$elem( "gsui-slider", { type: "linear-x", step: .01, min: -1, max: 1, "mousemove-size": 1600 } ),
	),
	$.$elem( "gsui-fx-delay-graph", null,
		$.$elem( "gsui-fx-delay-graph-lines", null,
			$.$elem( "gsui-beatlines", { timedivision: "4/4", color: "#fff" } ),
			$.$elem( "gsui-fx-delay-graph-line" ),
			$.$elem( "gsui-fx-delay-graph-source" ),
		),
		GSUnewArray( 20, () => $.$elem( "gsui-fx-delay-graph-echo" ) ),
	),
] );
