"use strict";

GSUsetTemplate( "gsui-fx-delay", () => [
	$.$div( { class: "gsuiEffect-param-row", "data-prop": "time" },
		$.$elem( "gs-label", null, "time" ),
		$.$elem( "gs-output" ),
		$.$elem( "gsui-slider", { type: "linear-x", step: .01, min: 0, max: 2, "mousemove-size": 1600 } ),
	),
	$.$div( { class: "gsuiEffect-param-row", "data-prop": "gain" },
		$.$elem( "gs-label", null, "gain" ),
		$.$elem( "gs-output" ),
		$.$elem( "gsui-slider", { type: "linear-x", step: .01, min: 0, max: .95, "mousemove-size": 1600 } ),
	),
	$.$div( { class: "gsuiEffect-param-row", "data-prop": "pan" },
		$.$elem( "gs-label", null, "pan" ),
		$.$elem( "gs-output" ),
		$.$elem( "gsui-slider", { type: "linear-x", step: .01, min: -1, max: 1, "mousemove-size": 1600 } ),
	),
	$.$div( { class: "gsuiFxDelay-graph" },
		$.$div( { class: "gsuiFxDelay-graph-lines" },
			$.$elem( "gsui-beatlines", { timedivision: "4/4", color: "#fff" } ),
			$.$div( { class: "gsuiFxDelay-graph-line" } ),
			$.$div( { class: "gsuiFxDelay-graph-source" } ),
		),
		GSUnewArray( 20, () => $.$div( { class: "gsuiFxDelay-graph-echo" } ) ),
	),
] );
