"use strict";

GSUsetTemplate( "gsui-fx-delay", () => [
	GSUcreateDiv( { class: "gsuiEffect-param-row", "data-prop": "time" },
		GSUcreateElement( "gs-label", null, "time" ),
		GSUcreateElement( "gs-output" ),
		GSUcreateElement( "gsui-slider", { type: "linear-x", step: .01, min: 0, max: 2 } ),
	),
	GSUcreateDiv( { class: "gsuiEffect-param-row", "data-prop": "gain" },
		GSUcreateElement( "gs-label", null, "gain" ),
		GSUcreateElement( "gs-output" ),
		GSUcreateElement( "gsui-slider", { type: "linear-x", step: .01, min: 0, max: .95 } ),
	),
	GSUcreateDiv( { class: "gsuiEffect-param-row", "data-prop": "pan" },
		GSUcreateElement( "gs-label", null, "pan" ),
		GSUcreateElement( "gs-output" ),
		GSUcreateElement( "gsui-slider", { type: "linear-x", step: .01, min: -1, max: 1 } ),
	),
	GSUcreateDiv( { class: "gsuiFxDelay-graph" },
		GSUcreateDiv( { class: "gsuiFxDelay-graph-lines" },
			GSUcreateElement( "gsui-beatlines", { timedivision: "4/4", color: "#fff" } ),
			GSUcreateDiv( { class: "gsuiFxDelay-graph-line" } ),
			GSUcreateDiv( { class: "gsuiFxDelay-graph-source" } ),
		),
		GSUnewArray( 20, () => GSUcreateDiv( { class: "gsuiFxDelay-graph-echo" } ) ),
	),
] );
