"use strict";

const GSTXall = GSUdeepFreeze( {
	en: {
		$all:          "all",
		$bio:          "bio",
		$you:          "you",
		$like:         "like",
		$liked:        "liked",
		$user:         "user",
		$with:         "with",
		$email:        "email",
		$reset:        "reset",
		$music:        "music",
		$delete:       "delete",
		$signIn:       "Sign in",
		$signUp:       "Sign up",
		$avatar:       "avatar",
		$cancel:       "cancel",
		$loading:      "loading…",
		$lastName:     "last name",
		$firstName:    "first name",
		$followers:    "followers",
		$following:    "following",
		$connection:   "Connection",
		$recycleBin:   "Recycle bin",
		$searchDots:   "search…",
		$startingDots: "starting…",
		// .....................................................................
		$composition: "composition",
		$synthesizer: "synthesizer",
		$patterns:    "patterns",
		$slicer:      "slicer",
		$mixer:       "mixer",
		$drums:       "drums",
		$piano:       "piano",
		// .....................................................................
		$tryMe:        "try me",
		$likedBy:      "liked by",
		$editBio:      "edit bio",
		$saveBio:      "save bio",
		$logInToGS:    "Log in to GridSound",
		$searchOnGS:   "Search a user or a composition on GridSound",
		$forkedFrom:   "based on",
		$emailPublic:  "email public",
		$clickToStart: "[ click to start ]",
		$checkVersion: "check the version",
		$writeYourBio: "Write your bio",
		$readTheirBio: "Read <i>$0</i>'s bio",
		$noBioWritten: "No bio written yet…",
		// .....................................................................
		$explore_all:  "Browse what is happening on <i>GridSound</i>.",
		$explore_you:  "Browse the last activities of your <b>$0</b> following.",
		$explore_you1: "Browse the last activities of your first following.",
		$explore_you0: "You have no following yet. Click on <bi>All</bi> to see the activities of every one.",
		// .....................................................................
		$search_user_0:   "There is no user matching <bi>\"$0\"</bi>",
		$search_cmps_0:   "There is no composition matching <bi>\"$0\"</bi>",
		$search_user_1:   "There is only one user matching <bi>\"$0\"</bi>",
		$search_cmps_1:   "There is only one composition matching <bi>\"$0\"</bi>",
		$search_user_n:   "There are $1 users matching <bi>\"$0\"</bi>",
		$search_cmps_n:   "There are $1 compositions matching <bi>\"$0\"</bi>",
		$search_user_max: "There are at least $1 users matching <bi>\"$0\"</bi>",
		$search_cmps_max: "There are at least $1 compositions matching <bi>\"$0\"</bi>",
		// .....................................................................
		$copyright:        `© ${ $.$year } gridsound.com All rights reserved`,
		$startCreatingNow: "Start creating your own music online",
		$gravatarWarn:     "GridSound accepts, for the moment, only <a https://gravatar.com>WordPress - Gravatar</a> as avatar.",
		$emailPublicWarn:  "if checked, your email will be public on your profile",
		$emailChangeWarn:  "if the email is changed, a confirmation email has to be sent again",
		$createNewCmp:     "<b>Create</b> a new composition",
		$exploreNewThings: "<b>Explore</b> new creations",
		$searchUsersCmps:  "<b>Search</b> for users and compositions",
		$yourMusicsPH:     "You have no composition yet, start creating one by clicking the <i>music-plus</i> button in the header.",
		$yourLikesPH:      "You didn't find any composition to like yet, start searching some by clicking on the <i>magnify-glass</i> icon.",
		$theirMusicsPH:    "There is, for the moment no composition to listen here.",
		$theirLikesPH:     "This user has liked no other composition until now.",
		// .....................................................................
		$user_login:           "Login / connection",
		$user_logout:          "Logout / disconnect",
		$user_untitled:        "Untitled",
		$user_saveCmp:         "<b>Save</b> composition",
		$user_renameCmp:       "Edit composition's title",
		$user_goProfile:       "Go to your <b>profile</b>",
		$user_pass:            "Password",
		$user_passForgot:      "Forgot password ?",
		$user_newAccount:      "Create a new account",
		$user_usernameOrEmail: "Username (or email)",
		// .....................................................................
		$player_openInDAW:      "<b>Open</b> in the DAW",
		$player_isPrivate:      "This composition is <b>private</b>",
		$player_isOpensource:   "This composition is <b>open-source</b>",
		$player_notRendered:    "This composition hasn't yet been rendered by its author",
		$player_noTurntable:    "This composition <b>has to be rendered</b> before using the <i>turntable</i>",
		$player_openTurntable:  "<b>Open</b> the tiny <i>turntable</i>",
		$player_closeTurntable: "<b>Close</b> the tiny <i>turntable</i>",
		// .....................................................................
		$player_opensourceIt: "Make it open-source",
		$player_publicIt:     "Make it public",
		$player_privateIt:    "Make it private",
		$player_forkIt:       "Fork it",
		$player_deleteIt:     "Delete it",
		$player_restoreIt:    "Restore it",
		// .....................................................................
		$player_opensourceDesc: "The world will be able to listen to your music and will have access to the source and be able to fork/copy it.",
		$player_publicDesc:     "The world will be able to listen to your music, without the source (only the rendered file).",
		$player_privateDesc:    "Only you will see the composition, no one will be able to listen it online.",
		$player_forkDesc:       "Copy the composition to your profile to apply the changes you want.",
		$player_deleteDesc:     "The composition will stay in your private bin for 30 days (only premium users have access to the bin).",
		$player_restoreDesc:    "Get the composition out of the bin.",
		// .....................................................................
		$about_gridsound:  "GridSound is a <b>work-in-progress</b> free browser-based digital audio workstation following the <a https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API>Web Audio API</a>.",
		$about_gridsound2: "You can create an account (by clicking the profile icon on the top-left corner) and start uploading your compositions online.",
		// .....................................................................
		$daw_gain:        "Main app <b>volume</b> (this will not affect the rendering)",
		$daw_focus:       "Switch <b>focus</b> between the composition and piano windows",
		$daw_reboot:      "<b>Reboot</b> the audio engine",
		$daw_undo:        "<b>Undo</b> the previous action",
		$daw_redo:        "<b>Redo</b> the last action",
		$daw_render:      "<b>Render</b> the composition",
		$daw_settings:    "Settings",
		$daw_openWindow:  "Open the <b>$0</b> window",
		$daw_closeWindow: "Close the <b>$0</b> window",
		$daw_showHelp:    "Show <b>help</b> links [❓] and tooltips",
		$daw_hideHelp:    "Hide <b>help</b> links [❓] and tooltips",
		$daw_about:       "About <i>GridSound</i> 🎵🎶",
		$daw_changelog:   "Read the <b>changelog</b>",
		// .....................................................................
		$patterns_createSlices:  "<b>Create</b> a new <b>slices</b> pattern",
		$patterns_createDrums:   "<b>Create</b> a new <b>drums</b> pattern",
		$patterns_createSynth:   "<b>Create</b> a new <b>synthesizer</b>",
		$patterns_createAutomat: "<b>Create</b> a new <b>automation</b> pattern",
		$patterns_placehBuffer:  "No buffer in use yet",
		$patterns_placehSlices:  "no slices yet",
		$patterns_placehDrums:   "no drums yet",
		$patterns_placehSynths:  "no synth yet",
		$patterns_placehAutomat: "no automation yet",
		// .....................................................................
		$library_placehUser: "drag'n drop your own samples in the app, they will appear here",
		// .....................................................................
		$win_rename_keys:   "<b>Rename</b> this keys pattern",
		$win_rename_synth:  "<b>Rename</b> this synthesizer",
		$win_rename_drums:  "<b>Rename</b> this drums pattern",
		$win_rename_slices: "<b>Rename</b> this slices pattern",
		$win_autoscroll:    "Auto scrolling",
		// .....................................................................
		$clock_switch: "Switch <b>beat</b> or <b>second</b> unit",
		$clock_second: "sec",  // 4 char max
		$clock_beat:   "beat", // 4 char max
		// .....................................................................
		$tempo_edit: "Edit <b>BPM</b> + <b>time signature</b>",
		$tempo_tap:  "Hit that button in rhythm<br/>it will calculate the <b>BPM</b>",
		// .....................................................................
		$timewindow_zoomX: "Zoom X",
		$timewindow_zoomY: "Zoom Y",
		// .....................................................................
		$track_mute:   "<b>Mute</b> track (right click for solo)",
		$track_unmute: "<b>Unmute</b> track (right click for solo)",
		$track_rename: "Double-click to <b>rename</b> track",
		// .....................................................................
		$stepSelect_snap: "Grid snap<br/> * click = <b>increase</b> the precision<br/> * right-click = <b>reduce</b> the precision",
		// .....................................................................
		$patterns_redirectSynth:   "<b>Redirect</b> this synthesizer",
		$patterns_createKeys:      "<b>Create</b> a new <b>keys</b> pattern with this synthesizer",
		$patterns_deleteSynth:     "<b>Delete</b> this synthesizer and its patterns",
		$patterns_editPatternInfo: "<b>Edit</b> this buffer pattern's info",
		$patterns_redirectPattern: "<b>Redirect</b> this pattern",
		$patterns_clonePattern:    "<b>Clone</b> this pattern",
		$patterns_deletePattern:   "<b>Delete</b> this pattern",
		// .....................................................................
		$mixer_channels:   "channels",
		$mixer_effects:    "effects",
		$mixer_timeDomain: "timeDomain",
		$mixer_frequency:  "frequency",
		$mixer_visu:       "Switch visualisation type",
		// .....................................................................
		$channels_vu:  "VU of the <b>selected channel</b><br/>🔴 = over 100% (the graphic goes to 120%)",
		$channels_add: "Add a channel",
		// .....................................................................
		$channel_rename: "Double-click to <b>rename</b> the channel",
		$channel_remove: "<b>Remove</b> the channel",
		$channel_pan:    "Left/right panning",
		$channel_gain:   "Gain, volume",
		$channel_mute:   "<b>Mute</b> the channel",
		$channel_unmute: "<b>Unmute</b> the channel",
		// .....................................................................
		$effects_add:             "<b>Add</b> an effect",
		$effects_filter:          "Filter",
		$effects_delay:           "Delay",
		$effects_reverb:          "Reverb",
		$effects_waveshaper:      "WaveShaper",
		$effects_filter_desc:     "LowPass, HighPass, BandPass, LowShelf, etc.",
		$effects_delay_desc:      "Echo, left/right ping-pong",
		$effects_reverb_desc:     "Convolution reverberation",
		$effects_waveshaper_desc: "Distortion, reshaping the wave with another wave",
		// .....................................................................
		$effect_mute:   "<b>Mute</b> this effect",
		$effect_unmute: "<b>Unmute</b> this effect",
		$effect_remove: "<b>Delete</b> this effect",
		// .....................................................................
		$drumrow_mute:   "<b>Mute</b> the drumrow (right click for solo)",
		$drumrow_unmute: "<b>Unmute</b> the drumrow (right click for solo)",
		$drumrow_expand: "<b>Expand</b> the props panel",
		$drumrow_close:  "<b>Close</b> the props panel",
		$drumrow_remove: "<b>Remove</b> the drumrow",
		// .....................................................................
		$oscillator_prevWave:  "Previous wave",
		$oscillator_nextWave:  "Next wave",
		$oscillator_wavetable: "<b>Wavetable</b> editor",
		$oscillator_remove:    "<b>Remove</b> the oscillator",
		// .....................................................................
		$wavetable_back:       "<b>Save and close</b> the wavetable",
		$wavetable_cloneWave:  "<b>Clone</b> this wave",
		$wavetable_removeWave: "<b>Remove</b> this wave",
		// .....................................................................
		$waveEditor_toggleSymm: "Toggle <b>symmetry</b>",
		// .....................................................................
		$automation_selectTarget: "Select automation's target",
		// .....................................................................
		$slicer_move:  "<b>Move</b> slices vertically",
		$slicer_reset: "<b>Reset</b> slices vertically",
		$slicer_cut:   "<b>Cut</b> slices in half",
		$slicer_merge: "<b>Merge</b> slices together",
		// .....................................................................
		$dotline_hold:         "hold",
		$dotline_curve:        "curve",
		$dotline_doubleCurve:  "double curve",
		$dotline_stair:        "stair",
		$dotline_sineWave:     "sine wave",
		$dotline_triangleWave: "triangle wave",
		$dotline_squareWave:   "square wave",
		// .....................................................................
		$helpLink_open: "Open the <b>$0</b> help page",
	},
	fr: {
		$all:          "tout",
		$bio:          "bio",
		$you:          "vous",
		$like:         "j'aime",
		$liked:        "à aimé",
		$user:         "utilisateur",
		$with:         "avec",
		$email:        "email",
		$reset:        "reset",
		$music:        "musique",
		$delete:       "supprimer",
		$signIn:       "Se connecter",
		$signUp:       "Créer son compte",
		$avatar:       "avatar",
		$cancel:       "annuler",
		$loading:      "chargement…",
		$lastName:     "nom",
		$firstName:    "prénom",
		$followers:    "abonnés",
		$following:    "abonnements",
		$connection:   "Connexion",
		$recycleBin:   "Corbeille",
		$searchDots:   "chercher…",
		$startingDots: "Démarrage…",
		// .....................................................................
		$composition: "composition",
		$synthesizer: "synthétiseur",
		$patterns:    "patterns",
		$slicer:      "slicer",
		$mixer:       "mixer",
		$drums:       "drums",
		$piano:       "piano",
		// .....................................................................
		$tryMe:        "try me",
		$likedBy:      "aimé par",
		$editBio:      "modifier la bio",
		$saveBio:      "enregistrer la bio",
		$logInToGS:    "Se connecter à GridSound",
		$searchOnGS:   "Chercher un utilisateur ou une composition sur GridSound",
		$forkedFrom:   "basé sur",
		$emailPublic:  "email public",
		$clickToStart: "[ cliquez pour démarrer ]",
		$checkVersion: "vérifier la version",
		$writeYourBio: "Rédigez votre bio",
		$readTheirBio: "Lire la bio de <i>$0</i>",
		$noBioWritten: "Aucune bio rédigée pour l'instant…",
		// .....................................................................
		$explore_all:  "Explorez ce qu'il se passe sur <i>GridSound</i>.",
		$explore_you:  "Explorez les dernières activités de vos <b>$0</b> abonnements.",
		$explore_you1: "Explorez les dernières activités de votre abonnement.",
		$explore_you0: "Vous n'avez encore aucun abonnement. Cliquez sur <bi>Tout</bi> pour voir les activités de tout le monde",
		// .....................................................................
		$search_user_0:   "Il n'y a aucun utilisateur correspondant à <bi>\"$0\"</bi>",
		$search_cmps_0:   "Il n'y a aucune composition correspondant à <bi>\"$0\"</bi>",
		$search_user_1:   "Il y a un seul utilisateur correspondant à <bi>\"$0\"</bi>",
		$search_cmps_1:   "Il y a une seule composition correspondant à <bi>\"$0\"</bi>",
		$search_user_n:   "Il y a $1 utilisateurs correspondant à <bi>\"$0\"</bi>",
		$search_cmps_n:   "Il y a $1 compositions correspondant à <bi>\"$0\"</bi>",
		$search_user_max: "Il y a au moins $1 utilisateurs correspondant à <bi>\"$0\"</bi>",
		$search_cmps_max: "Il y a au moins $1 compositions correspondant à <bi>\"$0\"</bi>",
		// .....................................................................
		$copyright:        `© ${ $.$year } gridsound.com Tous droits réservés`,
		$startCreatingNow: "Écrivez votre propre musique en ligne",
		$gravatarWarn:     "GridSound accepte, pour le moment, uniquement <a https://gravatar.com>WordPress - Gravatar</a> comme avatar.",
		$emailPublicWarn:  "si coché, votre email sera visible sur votre profil",
		$emailChangeWarn:  "si l'email est modifié, un email de confirmation devra être renvoyé",
		$createNewCmp:     "<b>Commencer</b> une nouvelle composition",
		$exploreNewThings: "<b>Explorer</b> de nouvelles choses",
		$searchUsersCmps:  "<b>Chercher</b> des musiciens et des compositions",
		$yourMusicsPH:     "Vous n'avez pas encore de composition, cliquez sur le button <i>music-plus</i> du haut pour en écrire une.",
		$yourLikesPH:      "Vous n'avez pas encore trouvé de composition qui mérite un like, cherchez-en en cliquant sur l'icône <i>loupe</i> du haut.",
		$theirMusicsPH:    "Il n'y a, pour le moment aucune composition à écouter ici.",
		$theirLikesPH:     "Cette personne n'a aimé aucune autre composition jusqu'à maintenant.",
		// .....................................................................
		$user_login:           "Connexion / identification",
		$user_logout:          "Déconnexion",
		$user_untitled:        "Sans-titre",
		$user_saveCmp:         "<b>Enregistrer</b> la composition",
		$user_renameCmp:       "Modifier le titre de la composition",
		$user_goProfile:       "Aller à votre <b>profil</b>",
		$user_pass:            "Mot de passe",
		$user_passForgot:      "Mot de passe oublié ?",
		$user_newAccount:      "Créer un nouveau compte",
		$user_usernameOrEmail: "Username (ou email)",
		// .....................................................................
		$player_openInDAW:      "<b>Ouvrir</b> dans le DAW",
		$player_isPrivate:      "Cette composition est <b>privée</b>",
		$player_isOpensource:   "Cette composition est <b>open-source</b>",
		$player_notRendered:    "Cette composition n'a pas encore été exporté par son auteur",
		$player_noTurntable:    "Cette composition <b>doit être exporté</b> avant d'utiliser la <i>platine</i>",
		$player_openTurntable:  "<b>Ouvrir</b> la mini <i>platine</i>",
		$player_closeTurntable: "<b>Fermer</b> la mini <i>platine</i>",
		// .....................................................................
		$player_opensourceIt: "Mettre la composition open-source",
		$player_publicIt:     "Mettre la composition publique",
		$player_privateIt:    "Mettre la composition privée",
		$player_forkIt:       "Dupliquer",
		$player_deleteIt:     "Supprimer",
		$player_restoreIt:    "Restaurer",
		// .....................................................................
		$player_opensourceDesc: "Le monde entier pourra écouter votre musique et aura accès à la source pour en faire une reprise.",
		$player_publicDesc:     "Le monde entier pourra écouter votre musique, sans accès à la source (uniquement le fichier mp3).",
		$player_privateDesc:    "Vous seul pourrez voir la composition, personne ne pourra l'écouter en ligne.",
		$player_forkDesc:       "Faites une reprise de cette composition sur votre profil pour y apporter vos propres modifications.",
		$player_deleteDesc:     "La composition restera dans votre corbeille privée pendant 30 jours (seuls les utilisateurs premium ont accès à la corbeille).",
		$player_restoreDesc:    "Restaurer la composition depuis la corbeille.",
		// .....................................................................
		$about_gridsound:  "GridSound est une station audionumérique dans le navigateur, le projet est <b>en-construction</b>, gratuit et est basée sur l'<a https://developer.mozilla.org/fr/docs/Web/API/Web_Audio_API>API Web Audio</a>.",
		$about_gridsound2: "Vous pouvez créer un compte (en cliquant sur l'icône de profil en haut à gauche) et commencer à publier vos compositions en ligne.",
		// .....................................................................
		$daw_gain:        "<b>Volume</b> principal de l'application (n'affecte pas le rendu)",
		$daw_focus:       "Basculer le <b>focus</b> entre la composition et le piano",
		$daw_reboot:      "<b>Redémarrer</b> le moteur audio",
		$daw_undo:        "<b>Annuler</b> l'action précédente",
		$daw_redo:        "<b>Rétablir</b> la dernière action",
		$daw_render:      "<b>Exporter</b> la composition",
		$daw_settings:    "Paramètres",
		$daw_openWindow:  "Ouvrir la fenêtre <b>$0</b>",
		$daw_closeWindow: "Fermer la fenêtre <b>$0</b>",
		$daw_showHelp:    "Afficher les liens d'<b>aide</b> [❓] et les infobulles",
		$daw_hideHelp:    "Masquer les liens d'<b>aide</b> [❓] et les infobulles",
		$daw_about:       "À propos de <i>GridSound</i> 🎵🎶",
		$daw_changelog:   "Lire le <b>journal des modifications</b>",
		// .....................................................................
		$patterns_createSlices:  "<b>Créer</b> un nouveau pattern de <b>slices</b>",
		$patterns_createDrums:   "<b>Créer</b> un nouveau pattern de <b>batterie</b>",
		$patterns_createSynth:   "<b>Créer</b> un nouveau <b>synthétiseur</b>",
		$patterns_createAutomat: "<b>Créer</b> un nouveau pattern d'<b>automation</b>",
		$patterns_placehBuffer:  "Aucun buffer en cours d'utilisation",
		$patterns_placehSlices:  "aucun slice pour l'instant",
		$patterns_placehDrums:   "aucune batterie pour l'instant",
		$patterns_placehSynths:  "aucun synthé pour l'instant",
		$patterns_placehAutomat: "aucune automation pour l'instant",
		// .....................................................................
		$library_placehUser: "glissez-déposez vos propres samples dans l'application, ils apparaîtront ici",
		// .....................................................................
		$win_rename_keys:   "<b>Renommer</b> ce pattern de touches",
		$win_rename_synth:  "<b>Renommer</b> ce synthétiseur",
		$win_rename_drums:  "<b>Renommer</b> ce pattern de batterie",
		$win_rename_slices: "<b>Renommer</b> ce pattern de slices",
		$win_autoscroll:    "Défilement automatique",
		// .....................................................................
		$clock_switch: "Basculer entre l'unité <b>temps</b> et <b>seconde</b>",
		$clock_second: "sec",  // 4 char max
		$clock_beat:   "tmps", // 4 char max
		// .....................................................................
		$tempo_edit: "Modifier le <b>BPM</b> et la <b>signature rythmique</b>",
		$tempo_tap:  "Tapez ce bouton en rythme<br/>il calculera le <b>BPM</b>",
		// .....................................................................
		$timewindow_zoomX: "Zoom X",
		$timewindow_zoomY: "Zoom Y",
		// .....................................................................
		$track_mute:   "<b>Désactiver</b> la piste (clic droit pour solo)",
		$track_unmute: "<b>Réactiver</b> la piste (clic droit pour solo)",
		$track_rename: "Double-cliquer pour <b>renommer</b> la piste",
		// .....................................................................
		$stepSelect_snap: "Grille magnétisme<br/> * clic = <b>augmenter</b> la précision<br/> * clic droit = <b>réduire</b> la précision",
		// .....................................................................
		$patterns_redirectSynth:   "<b>Rediriger</b> ce synthétiseur",
		$patterns_createKeys:      "<b>Créer</b> un nouveau pattern de <b>touches</b> avec ce synthétiseur",
		$patterns_deleteSynth:     "<b>Supprimer</b> ce synthétiseur et ses patterns",
		$patterns_editPatternInfo: "<b>Modifier</b> les informations de ce pattern buffer",
		$patterns_redirectPattern: "<b>Rediriger</b> ce pattern",
		$patterns_clonePattern:    "<b>Cloner</b> ce pattern",
		$patterns_deletePattern:   "<b>Supprimer</b> ce pattern",
		// .....................................................................
		$mixer_channels:   "canaux",
		$mixer_effects:    "effets",
		$mixer_timeDomain: "domaineTempo",
		$mixer_frequency:  "fréquence",
		$mixer_visu:       "Changer le type de visualisation",
		// .....................................................................
		$channels_vu:  "VU du <b>canal sélectionné</b><br/>🔴 = au dessus de 100% (l'affichage va jusqu'à 120%)",
		$channels_add: "Ajouter un canal",
		// .....................................................................
		$channel_rename: "Double-cliquer pour <b>renommer</b> le canal",
		$channel_remove: "<b>Supprimer</b> le canal",
		$channel_pan:    "Panoramique gauche/droite",
		$channel_gain:   "Gain, volume",
		$channel_mute:   "<b>Désactiver</b> le canal",
		$channel_unmute: "<b>Réactiver</b> le canal",
		// .....................................................................
		$effects_add:             "<b>Ajouter</b> un effet",
		$effects_filter:          "Filtre",
		$effects_delay:           "Délai",
		$effects_reverb:          "Réverb",
		$effects_waveshaper:      "WaveShaper",
		$effects_filter_desc:     "Passe-bas, passe-haut, passe-bande, plateau-bas, etc.",
		$effects_delay_desc:      "Echo, ping-pong gauche/droite",
		$effects_reverb_desc:     "Réverbération par convolution",
		$effects_waveshaper_desc: "Distorsion, remodeler l'onde avec une autre onde",
		// .....................................................................
		$effect_mute:   "<b>Désactiver</b> cet effet",
		$effect_unmute: "<b>Activer</b> cet effet",
		$effect_remove: "<b>Supprimer</b> cet effet",
		// .....................................................................
		$drumrow_mute:   "<b>Désactiver</b> la ligne de batterie (clic droit pour solo)",
		$drumrow_unmute: "<b>Réactiver</b> la ligne de batterie (clic droit pour solo)",
		$drumrow_expand: "<b>Développer</b> le panneau des propriétés",
		$drumrow_close:  "<b>Fermer</b> le panneau des propriétés",
		$drumrow_remove: "<b>Supprimer</b> la ligne de batterie",
		// .....................................................................
		$oscillator_prevWave:  "Forme d'onde précédente",
		$oscillator_nextWave:  "Forme d'onde suivante",
		$oscillator_wavetable: "Éditeur de <b>table d'ondes</b>",
		$oscillator_remove:    "<b>Supprimer</b> l'oscillateur",
		// .....................................................................
		$wavetable_back:       "<b>Enregistrer et fermer</b> la table d'ondes",
		$wavetable_cloneWave:  "<b>Cloner</b> cette onde",
		$wavetable_removeWave: "<b>Supprimer</b> cette onde",
		// .....................................................................
		$waveEditor_toggleSymm: "Activer/désactiver la <b>symétrie</b>",
		// .....................................................................
		$automation_selectTarget: "Sélectionner la cible de l'automation",
		// .....................................................................
		$slicer_move:  "<b>Déplacer</b> les slices verticalement",
		$slicer_reset: "<b>Réinitialiser</b> les slices verticalement",
		$slicer_cut:   "<b>Couper</b> les slices en deux",
		$slicer_merge: "<b>Fusionner</b> les slices",
		// .....................................................................
		$dotline_hold:         "constant",
		$dotline_curve:        "courbe",
		$dotline_doubleCurve:  "double courbe",
		$dotline_stair:        "escalier",
		$dotline_sineWave:     "onde sinus",
		$dotline_triangleWave: "onde triangle",
		$dotline_squareWave:   "onde carrée",
		// .....................................................................
		$helpLink_open: "Ouvrir la page d'aide pour <b>$0</b>",
	},
} );

const GSTX = GSTXall[ $.$lang() ] || GSTXall.en;

const GSTXplural = ( w, nb ) => nb < 2 || w.endsWith( "s" ) ? w : `${ w }s`;
const GSTXreplace = ( s, ...arr ) => GSUreduce( arr, ( s, a, i ) => s.replaceAll( `$${ i }`, a ), s );

if ( __LOCALHOST__ ) {
	const keys = GSUmap( GSTXall, obj => Object.keys( obj ).toString() );
	const err = GSUfindIndex( keys, str => str !== keys.en );

	if ( err !== -1 ) {
		console.warn( `GSTX: something wrong with "${ err }"` );
	}
}
