"use strict";

GSUI.setTemplate( "gsui-controls", () => [
	GSUI.createElement( "div", { class: "gsuiControls-head" },
		GSUI.createElement( "div", { class: "gsuiControls-area gsuiControls-areaUser" },
			GSUI.createElement( "span",   { class: "gsuiControls-title" }, "GridSound" ),
			GSUI.createElement( "a",      { class: "gsuiControls-btn", "data-action": "profile", href: true, title: "Cloud profile", target: "_blank", rel: "noopener" } ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-btnBig gsuiIcon", "data-action": "login",  "data-icon": "profile", title: "Login to GridSound" } ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-btnBig gsuiIcon", "data-action": "logout", "data-icon": "logout",  title: "Logout" } ),
			GSUI.createElement( "div", { class: "gsuiControls-cmps" },
				GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-btnBig gsuiControls-btnColor gsuiIcon", "data-action": "cmps", "data-icon": "musics", title: "Create cloud/local compositions" } ),
				GSUI.getTemplate( "gsui-controls-cmps" ),
				GSUI.createElement( "div", { class: "gsuiControls-dropdown-backdrop" } ),
			),
		),
		GSUI.createElement( "div", { class: "gsuiControls-area gsuiControls-areaSave gsuiControls-btns" },
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-btnColor gsuiControls-cmp-saveBtn gsuiIcon", "data-action": "save", title: "Save composition" } ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-cmp-editBtn", "data-action": "rename", title: "Edit composition's title" },
				GSUI.createElement( "i",    { class: "gsuiControls-cmp-localIcon gsuiIcon" } ),
				GSUI.createElement( "span", { class: "gsuiControls-cmp-name" } ),
				GSUI.createElement( "i",    { class: "gsuiControls-cmp-editIcon gsuiIcon", "data-icon": "pen" } ),
				GSUI.createElement( "span", { class: "gsuiControls-cmp-dur" }, "0:45" ),
			),
		),
		GSUI.createElement( "div", { class: "gsuiControls-area gsuiControls-areaCtrl" },
			GSUI.createElement( "div", { class: "gsuiControls-volume", title: "Main app volume (this will not affect the rendering)" },
				GSUI.createElement( "gsui-slider", { "data-action": "volume", type: "linear-y", min: 0, max: 1, step: .01, "mousemove-size": 150 } ),
			),
			GSUI.createElement( "div", { class: "gsuiControls-btns gsuiControls-playPauseStop" },
				GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-focusBtn", "data-action": "focusSwitch", "data-dir": "up", title: "Toggle focus between the composition and piano windows" },
					GSUI.createElement( "span" ),
					GSUI.createElement( "span" ),
				),
				GSUI.createElement( "button", { class: "gsuiControls-btn gsuiIcon", "data-action": "play",  "data-icon": "play" } ),
				GSUI.createElement( "button", { class: "gsuiControls-btn gsuiIcon", "data-action": "stop",  "data-icon": "stop" } ),
				GSUI.createElement( "button", { class: "gsuiControls-btn gsuiIcon", "data-action": "reset", "data-icon": "sync", title: "Restart the audio engine" } ),
			),
			GSUI.createElement( "gsui-clock" ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-tempo", "data-action": "tempo", title: "Edit the time signature and BPM" },
				GSUI.createElement( "div", { class: "gsuiControls-tempo-timeDivision" },
					GSUI.createElement( "span", { class: "gsuiControls-tempo-beatsPerMeasure" } ),
					GSUI.createElement( "span", { class: "gsuiControls-tempo-stepsPerBeat" } ),
				),
				GSUI.createElement( "span", { class: "gsuiControls-tempo-bpm" } ),
			),
		),
		GSUI.createElement( "div", { class: "gsuiControls-area gsuiControls-areaTime" },
			GSUI.createElement( "gsui-slider", { "data-action": "currentTime", type: "linear-x", min: 0, step: .01 } ),
		),
		GSUI.createElement( "div", { class: "gsuiControls-area gsuiControls-areaHist" },
			GSUI.createElement( "div", { class: "gsuiControls-btns gsuiControls-history" },
				GSUI.createElement( "button", { class: "gsuiControls-btn gsuiIcon",                           "data-action": "undo",     "data-icon": "undo",       title: "Undo the previous action" } ),
				GSUI.createElement( "button", { class: "gsuiControls-btn gsuiIcon",                           "data-action": "redo",     "data-icon": "redo",       title: "Redo the last action" } ),
				GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-dropdown-btn gsuiIcon", "data-action": "undoMore", "data-icon": "caret-down", title: "Show the actions list" } ),
				GSUI.getTemplate( "gsui-controls-history" ),
				GSUI.createElement( "div", { class: "gsuiControls-dropdown-backdrop" } ),
			),
			GSUI.createElement( "gsui-spectrum" ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-btnBg gsuiControls-btnColor gsuiIcon", "data-action": "export",   "data-icon": "export",   title: "Export the composition" } ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-btnBg gsuiIcon", "data-action": "settings", "data-icon": "settings", title: "Settings" } ),
		),
		GSUI.createElement( "div", { class: "gsuiControls-area gsuiControls-areaWins gsuiControls-btns" },
			GSUI.createElement( "button", { "data-open": "", class: "gsuiControls-btn gsuiIcon", "data-icon": "folder-tree", "data-win": "blocks",  title: "Open/close the blocks window" } ),
			GSUI.createElement( "button", { "data-open": "", class: "gsuiControls-btn gsuiIcon", "data-icon": "mixer",       "data-win": "mixer",   title: "Open/close the mixer window" } ),
			GSUI.createElement( "button", { "data-open": "", class: "gsuiControls-btn gsuiIcon", "data-icon": "music",       "data-win": "main",    title: "Open/close the composition window" } ),
			GSUI.createElement( "button", { "data-open": "", class: "gsuiControls-btn gsuiIcon", "data-icon": "oscillator",  "data-win": "synth",   title: "Open/close the synthesizer window" } ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiIcon", "data-icon": "drums",       "data-win": "drums",   title: "Open/close the drums window" } ),
			GSUI.createElement( "button", { "data-open": "", class: "gsuiControls-btn gsuiIcon", "data-icon": "keys",        "data-win": "piano",   title: "Open/close the piano window" } ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiIcon", "data-icon": "slices",      "data-win": "slicer",  title: "Open/close the slices window" } ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiIcon", "data-icon": "effects",     "data-win": "effects", title: "Open/close the effects window" } ),
		),
		GSUI.createElement( "div", { class: "gsuiControls-area gsuiControls-areaHelp" },
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-btnBg gsuiIcon",                       "data-action": "cookies",   "data-icon": "cookie",    title: "Cookies" } ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-btnBg gsuiIcon",                       "data-action": "keyboard",  "data-icon": "keyboard",  title: "Keyboard shortcuts" } ),
			GSUI.createElement( "a",      { class: "gsuiControls-btn gsuiControls-btnBg gsuiIcon",                       "data-action": "help",      "data-icon": "help",      title: "Help",      href: "https://github.com/gridsound/daw/wiki/help",      target: "_blank", rel: "noopener" } ),
			GSUI.createElement( "a",      { class: "gsuiControls-btn gsuiControls-btnBg gsuiIcon",                       "data-action": "changelog", "data-icon": "changelog", title: "Changelog", href: "https://github.com/gridsound/daw/wiki/changelog", target: "_blank", rel: "noopener" } ),
			GSUI.createElement( "button", { class: "gsuiControls-btn gsuiControls-btnBg gsuiControls-btnColor gsuiIcon", "data-action": "about",     "data-icon": "about",     title: "About" } ),
		),
		GSUI.createElement( "div", { class: "gsuiControls-area gsuiControls-areaVers" },
			GSUI.createElement( "a", { class: "gsuiControls-btn gsuiControls-version", "data-action": "version", title: "Access older versions", href: "https://github.com/gridsound/daw/wiki/versions", target: "_blank", rel: "noopener" },
				GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "list" } ),
				GSUI.createElement( "span", { class: "gsuiControls-version-num" }, "version" ),
			),
		),
	),
	GSUI.createElement( "div", { class: "gsuiControls-body" } ),
] );

GSUI.setTemplate( "gsui-controls-cmps", () => [
] );

GSUI.setTemplate( "gsui-controls-history", () => (
	GSUI.createElement( "div", { class: "gsuiControls-dropdown", tabindex: 0 },
		GSUI.createElement( "div", { class: "gsuiControls-dropdown-head", id: "historyTitle" },
			GSUI.createElement( "i", { class: "gsuiControls-dropdown-icon gsuiIcon", "data-icon": "history" } ),
			GSUI.createElement( "span", { class: "gsuiControls-dropdown-title" }, "history" ),
		),
		GSUI.createElement( "div", { class: "gsuiControls-dropdown-list", id: "historyList" },
			GSUI.createElement( "div", { class: "gsuiControls-dropdown-placeholder" },
				GSUI.createElement( "span", null, "there is nothing to undo" ),
			),
		),
	)
) );
