"use strict";

GSUsetTemplate( "gsui-timewindow", () => [
	GSUcreateElement( "div", { class: "gsuiTimewindow-panel" },
		GSUcreateElement( "div", { class: "gsuiTimewindow-panelUp" },
			GSUcreateElement( "button", { class: "gsuiTimewindow-step" },
				GSUcreateElement( "span", { class: "gsuiTimewindow-stepValue" } ),
				GSUcreateElement( "i", { class: "gsuiIcon", "data-icon": "magnet" } ),
			),
			GSUcreateElement( "gsui-slider", { "data-zoom": "y", type: "linear-y", "mousemove-size": 400, min: 0, max: 1, step: .01, title: "zooming Y" } ),
			GSUcreateElement( "gsui-slider", { "data-zoom": "x", type: "linear-y", "mousemove-size": 400, min: 0, max: 1, step: .01, title: "zooming X" } ),
		),
		GSUcreateElement( "div", { class: "gsuiTimewindow-panelContent" } ),
		GSUcreateElement( "div", { class: "gsuiTimewindow-panelContentDown" },
			GSUcreateElement( "div", { class: "gsuiTimewindow-panelExtend gsuiTimewindow-panelExtendX" } ),
		),
		GSUcreateElement( "div", { class: "gsuiTimewindow-panelExtend gsuiTimewindow-panelExtendY" } ),
	),
	GSUcreateElement( "div", { class: "gsuiTimewindow-main" },
		GSUcreateElement( "div", { class: "gsuiTimewindow-time" },
			GSUcreateElement( "gsui-timeline" ),
		),
		GSUcreateElement( "div", { class: "gsuiTimewindow-mainBody" },
			GSUcreateElement( "div", { class: "gsuiTimewindow-mainContent" },
				GSUcreateElement( "gsui-beatlines", { coloredbeats: "" } ),
				GSUcreateElement( "div", { class: "gsuiTimewindow-currentTime" } ),
				GSUcreateElement( "div", { class: "gsuiTimewindow-loop gsuiTimewindow-loopA" } ),
				GSUcreateElement( "div", { class: "gsuiTimewindow-loop gsuiTimewindow-loopB" } ),
				GSUcreateElement( "div", { class: "gsuiTimewindow-rows" } ),
			),
		),
		GSUcreateElement( "div", { class: "gsuiTimewindow-contentDown" },
			GSUcreateElement( "div", { class: "gsuiTimewindow-panelExtend gsuiTimewindow-panelExtendX" } ),
		),
	),
] );
