"use strict";

GSUI.setTemplate( "gsui-timewindow", () => [
	GSUI.createElem( "div", { class: "gsuiTimewindow-panel" },
		GSUI.createElem( "div", { class: "gsuiTimewindow-panelUp" },
			GSUI.createElem( "button", { class: "gsuiTimewindow-step" },
				GSUI.createElem( "span", { class: "gsuiTimewindow-stepValue" } ),
				GSUI.createElem( "i", { class: "gsuiIcon", "data-icon": "magnet" } ),
			),
		),
		GSUI.createElem( "div", { class: "gsuiTimewindow-panelContent" } ),
		GSUI.createElem( "div", { class: "gsuiTimewindow-panelContentDown" },
			GSUI.createElem( "div", { class: "gsuiTimewindow-panelExtend gsuiTimewindow-panelExtendX" } ),
		),
		GSUI.createElem( "div", { class: "gsuiTimewindow-panelExtend gsuiTimewindow-panelExtendY" } ),
	),
	GSUI.createElem( "div", { class: "gsuiTimewindow-main" },
		GSUI.createElem( "div", { class: "gsuiTimewindow-time" },
			GSUI.createElem( "gsui-timeline" ),
		),
		GSUI.createElem( "div", { class: "gsuiTimewindow-mainBody" },
			GSUI.createElem( "div", { class: "gsuiTimewindow-mainContent" },
				GSUI.createElem( "gsui-beatlines", { coloredbeats: "" } ),
				GSUI.createElem( "div", { class: "gsuiTimewindow-currentTime" } ),
				GSUI.createElem( "div", { class: "gsuiTimewindow-loop gsuiTimewindow-loopA" } ),
				GSUI.createElem( "div", { class: "gsuiTimewindow-loop gsuiTimewindow-loopB" } ),
				GSUI.createElem( "div", { class: "gsuiTimewindow-rows" } ),
			),
		),
		GSUI.createElem( "div", { class: "gsuiTimewindow-contentDown" },
			GSUI.createElem( "div", { class: "gsuiTimewindow-panelExtend gsuiTimewindow-panelExtendX" } ),
		),
	),
] );
