"use strict";

GSUsetTemplate( "gsui-com-player", () => [
	GSUcreateButton( { class: "gsuiComPlayer-btn gsuiComPlayer-play", icon: "play" } ),
	GSUcreateDiv( { class: "gsuiComPlayer-body" },
		GSUcreateDiv( { class: "gsuiComPlayer-text" },
			GSUcreateDiv( { class: "gsuiComPlayer-name" },
				GSUcreateA( { class: "gsuiComPlayer-nameLink", href: false } ),
			),
			GSUcreateDiv( { class: "gsuiComPlayer-info-wrap" },
				GSUcreateDiv( { class: "gsuiComPlayer-info" },
					GSUcreateDiv( { class: "gsuiComPlayer-time" },
						GSUcreateIcon( { icon: "clock" } ),
						GSUcreateSpan( { class: "gsuiComPlayer-currentTime" } ),
						GSUcreateSpan( { class: "gsuiComPlayer-duration" } ),
					),
					GSUcreateDiv( { class: "gsuiComPlayer-tempo" },
						GSUcreateIcon( { icon: "speed" } ),
						GSUcreateSpan( { class: "gsuiComPlayer-bpm" } ),
					),
				),
			),
		),
		GSUcreateDiv( { class: "gsuiComPlayer-slider" },
			GSUcreateDiv( { class: "gsuiComPlayer-sliderValue" } ),
			GSUcreateDiv( { class: "gsuiComPlayer-sliderInput" } ),
		),
	),
	GSUcreateAExt( { class: "gsuiComPlayer-btn gsuiComPlayer-dawlink", title: "Open in the DAW", href: false },
		GSUcreateIcon( { icon: "music" } ),
		GSUcreateIcon( { icon: "pen" } ),
		GSUcreateIcon( { icon: "eye" } ),
	),
	GSUcreateButton( { class: "gsuiComPlayer-btn gsuiComPlayer-actions", icon: "ellipsis-v" } ),
] );
