"use strict";

GSUsetTemplate( "gsui-com-player", () => [
	GSUcreateButton( { class: "gsuiComPlayer-btn gsuiComPlayer-play gsuiIcon", "data-icon": "play" } ),
	GSUcreateDiv( { class: "gsuiComPlayer-body" },
		GSUcreateDiv( { class: "gsuiComPlayer-text" },
			GSUcreateDiv( { class: "gsuiComPlayer-name" },
				GSUcreateA( { class: "gsuiComPlayer-nameLink", href: false } ),
			),
			GSUcreateDiv( { class: "gsuiComPlayer-info-wrap" },
				GSUcreateDiv( { class: "gsuiComPlayer-info" },
					GSUcreateDiv( { class: "gsuiComPlayer-time" },
						GSUcreateI( { class: "gsuiIcon", "data-icon": "clock" } ),
						GSUcreateSpan( { class: "gsuiComPlayer-currentTime" } ),
						GSUcreateSpan( { class: "gsuiComPlayer-duration" } ),
					),
					GSUcreateDiv( { class: "gsuiComPlayer-tempo" },
						GSUcreateI( { class: "gsuiIcon", "data-icon": "speed" } ),
						GSUcreateSpan( { class: "gsuiComPlayer-bpm" } ),
					),
				),
			),
		),
		GSUcreateDiv( { class: "gsuiComPlayer-slider" },
			GSUcreateDiv( { class: "gsuiComPlayer-sliderValue" } ),
			GSUcreateDiv( { class: "gsuiComPlayer-sliderInput" } ),
		),
	),
	GSUcreateAExt( { class: "gsuiComPlayer-btn gsuiComPlayer-dawlink", title: "Open in the DAW", href: false },
		GSUcreateI( { class: "gsuiIcon", "data-icon": "music", inert: true } ),
		GSUcreateI( { class: "gsuiIcon", "data-icon": "pen", inert: true } ),
		GSUcreateI( { class: "gsuiIcon", "data-icon": "eye", inert: true } ),
	),
	GSUcreateButton( { class: "gsuiComPlayer-btn gsuiComPlayer-actions gsuiIcon", "data-icon": "ellipsis-v" } ),
] );
