"use strict";

$.$setTemplate( "gsui-oscillator", () => {
	const popId = GSUuuid();

	return $.$elem( "gsui-osc-in", null,
		$.$elem( "gsui-osc-grip", null,
			$.$icon( { icon: "grip-v" } ),
		),
		$.$elem( "gsui-osc-id", { inert: true } ),
		$.$elem( "gsui-osc-head-label", null, "unison" ),
		$.$elem( "gsui-osc-head-label", null, "pitch" ),
		$.$elem( "gsui-osc-head-label", null, "pan" ),
		$.$elem( "gsui-osc-head-label", null, "gain" ),
		$.$elem( "gsui-osc-wavelet-browser-pop", { id: popId, popover: true } ),
		$.$elem( "gsui-osc-wave-column", null,
			$.$elem( "gsui-osc-wavewrap", null,
				$.$elem( "gsui-osc-wavewrap-left", {},
					$.$elem( "gsui-osc-wavewrap-top", { },
						$.$button( { "data-dir": "-1", "data-tooltip": GSTX.$oscillator_prevWave }, $.$icon( { icon: "caret-left" } ) ),
						$.$button( { "data-dir": "1", "data-tooltip": GSTX.$oscillator_nextWave }, $.$icon( { icon: "caret-right" } ) ),
						$.$button( { "data-action": "wave-name", popovertarget: popId } ),
						$.$button( { "data-action": "wave-edit", "data-tooltip": GSTX.$oscillator_wavetable }, $.$icon( { icon: "cu-wave-edit" } ) ),
						$.$icon( { icon: "cu-waveform" } ),
						$.$elem( "gsui-osc-srcname" ),
					),
					$.$elem( "gsui-osc-wavewrap-bottom", { inert: true },
						$.$elem( "gsui-osc-src", null ),
						$.$elem( "gsui-osc-wave", null,
							$.$elem( "gsui-periodicwave" ),
							$.$elem( "gsui-periodicwave" ),
						),
					),
				),
			),
			$.$elem( "gsui-slider", { type: "linear-x", min: 0, max: 1, step: .001, "mousemove-size": "400", "data-prop": "phaze", defaultValue: 0 } ),
		),
		$.$elem( "gsui-osc-unison", null,
			$.$elem( "gsui-osc-unison-graph", null,
				$.$elem( "gsui-osc-unison-voices" ),
			),
			$.$elem( "gsui-slider", { type: "linear-y", min: 1, max: 9, step: 1, "mousemove-size": "400", "data-prop": "unisonvoices", "data-tooltip": "Unison <b>voices</b>", defaultValue: 1 } ),
			$.$elem( "gsui-slider", { type: "linear-y", min: 0, max: 1, step: .001, "mousemove-size": "800", "data-prop": "unisondetune", "data-tooltip": "Unison <b>detune</b>" } ),
			$.$elem( "gsui-slider", { type: "linear-y", min: 0, max: 1, step: .001, "mousemove-size": "800", "data-prop": "unisonblend", "data-tooltip": "Unison <b>blend</b>" } ),
		),
		[
			[ "detune", -24, 24, 1, 0 ],
			[ "pan", -1, 1, .02, 0 ],
			[ "gain", 0, 1, .01, 1 ],
		].map( ( [ prop, min, max, step, def ] ) =>
			$.$elem( "gsui-osc-prop", { "data-prop": prop },
				$.$elem( "gsui-osc-slider-wrap", null,
					$.$elem( "gsui-slider", { type: "circular", min, max, step, "mousemove-size": "800", "data-prop": prop, defaultValue: def } ),
					prop !== "detune" ? null : $.$elem( "gsui-slider", { type: "circular", min: -1, max: 1, step: .01, "mousemove-size": "800", "data-prop": "detunefine", "stroke-width": 3, defaultValue: 0 } )
				),
				$.$elem( "gsui-osc-slider-val" ),
			)
		),
		$.$button( { "data-action": "remove", "data-tooltip": GSTX.$oscillator_remove },
			$.$icon( { icon: "close" } ),
		),
		$.$elem( "gsui-osc-wavetable" ),
	);
} );
