"use strict";

$.$setTemplate( "gsui-com-profile", () => [
	$.$div( { class: "gsuiComProfile-avatar" },
		$.$elem( "gsui-com-avatar" ),
	),
	$.$div( { class: "gsuiComProfile-info" },
		$.$div( { class: "gsuiComProfile-name gsui-ellipsis" },
			$.$span( { class: "gsuiComProfile-username gsui-ellipsis" } ),
			$.$span( { class: "gsuiComProfile-fullname gsui-ellipsis" } ),
		),
		$.$div( { class: "gsuiComProfile-email" },
			$.$span( { class: "gsuiComProfile-email-addr" },
				$.$icon( { icon: "private" } ),
				$.$span( { class: "gsui-ellipsis" } ),
			),
			$.$button( { class: "gsuiComProfile-email-not", "data-what": "verify" },
				$.$icon( { spin: true, inert: true } ),
				$.$span( { class: "gsui-ellipsis", inert: true } ),
			),
		),
		$.$div( { class: "gsuiComProfile-follow gsui-ellipsis" },
			$.$button( { "data-what": "followers" },
				$.$bold( { inert: true } ),
				$.$span( { class: "gsui-ellipsis", inert: true }, GSTX.$followers ),
			),
			$.$button( { "data-what": "following" },
				$.$bold( { inert: true } ),
				$.$span( { class: "gsui-ellipsis", inert: true }, GSTX.$following ),
			),
		),
	),
	$.$button( { class: "gsuiComProfile-edit", icon: "pen", "data-what": "edit" } ),
	$.$button( { class: "gsuiComProfile-follow-btn", "data-what": "follow" },
		$.$icon( { icon: "follow" } ),
		$.$icon( { icon: "followed" } ),
		$.$icon( { icon: "unfollow" } ),
	),
] );
