"use strict";

GSUI.setTemplate( "gsui-daw-popup-shortcuts", () => (
	GSUI.createElement( "div", { class: "gsuiDAW-popup-shortcuts" },
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Global shortcuts" ),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Save the current composition" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null, "S" ),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Open a composition" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null, "O" ),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Open a new composition" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Alt" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null, "N" ),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Play / pause the selected grid" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Space" ),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Undo the previous action" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null, "Z" ),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Redo the next action" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null, "Shift" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null, "Z" ),
				),
			),
		),
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Grids shortcuts" ),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Select all the blocks of the focused grid" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null, "A" ),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Deselect all the blocks of the focused grid" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null, "D" ),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Duplicate (copy/paste) the selected blocks" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null, "B" ),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Delete all the selected blocks of the focused grid" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Delete" ),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Move vertically inside the grids" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null,
						"Scroll ",
						GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "arrows-v" } ),
					),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Move horizontally inside the grids" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Shift" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null,
						"Scroll ",
						GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "arrows-v" } ),
					),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" },
					"Zoom-in / zoom-out", GSUI.createElement( "br" ),
					"Zoom X by scrolling above the grid", GSUI.createElement( "br" ),
					"Zoom Y by scrolling above the keys", GSUI.createElement( "br" ),
				),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "kbd", null, "Ctrl / ⌘" ),
					GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", null,
						"Scroll ",
						GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "arrows-v" } ),
					),
				),
			),
		),
	)
) );
