"use strict";

$.$setTemplate( "gsui-daw-windowHeads", () => [
	$.$div( { "data-window": "composition" },
		$.$getTemplate( "gsui-daw-window-playPause" ),
	),
	$.$div( { "data-window": "keys" },
		$.$button( { class: "gsuiDAW-winBtn", "data-target": "pianoroll" } ),
		$.$getTemplate( "gsui-daw-window-playPause" ),
	),
	$.$div( { "data-window": "synth" },
		$.$button( { class: "gsuiDAW-winBtn", "data-target": "synth" } ),
		$.$icon( { icon: "arrow-right" } ),
		$.$button( { class: "gsuiDAW-winBtn", "data-target": "synthChannel" },
			$.$icon( { icon: "mixer" } ),
			$.$span(),
		),
	),
	$.$div( { "data-window": "mixer" } ),
	$.$div( { "data-window": "drums" },
		$.$button( { class: "gsuiDAW-winBtn", "data-target": "drums" } ),
		$.$getTemplate( "gsui-daw-window-playPause" ),
	),
	$.$div( { "data-window": "slices" },
		$.$button( { class: "gsuiDAW-winBtn", "data-target": "slices" } ),
		$.$getTemplate( "gsui-daw-window-playPause" ),
	),
	$.$div( { "data-window": "automation" },
		$.$button( { class: "gsuiDAW-winBtn", "data-target": "automation" } ),
	),
] );

$.$setTemplate( "gsui-daw-window-playPause", () => [
	$.$div( { class: "gsuiDAW-window-ctrl" },
		$.$div( null,
			$.$button( { "data-action": "play", icon: "play" } ),
			$.$button( { "data-action": "stop", icon: "stop" } ),
		),
		$.$button( { "data-action": "autoscroll", icon: "chevrons-right", title: "Auto scrolling" } ),
	),
] );
