"use strict";

GSUsetTemplate( "gsui-daw-popup-about", () =>
	$.$div( { class: "gsuiDAW-popup-about" },
		$.$div( { class: "gsuiDAW-popup-about-head" },
			$.$span( { class: "gsuiDAW-popup-about-title" } ),
			$.$span( { class: "gsuiDAW-popup-about-versionNum" } ),
			$.$icon( null ),
			$.$button( { class: "gsuiDAW-popup-about-versionCheck" }, "check the version" ),
		),
		$.$div( null,
			"GridSound is a ",
			$.$bold( null, "work-in-progress" ),
			" free browser-based digital audio workstation following the ",
			$.$linkExt( { href: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API" }, "Web Audio API" ),
			".",
		),
		$.$div( null,
			"You can create an account (by clicking ", $.$icon( { icon: "profile" } ),
			") and start uploading your compositions online ", $.$icon( { icon: "cloud" } ),
		),
		$.$div( { class: "gsuiDAW-popup-about-links" },
			$.$linkExt( { title: "GitHub",   class: "gsuiIcon", "data-icon": "br-github",   href: "https://github.com/gridsound" } ),
			$.$linkExt( { title: "Bluesky",  class: "gsuiIcon", "data-icon": "br-bluesky",  href: "https://bsky.app/profile/gridsound.com" } ),
			$.$linkExt( { title: "YouTube",  class: "gsuiIcon", "data-icon": "br-youtube",  href: "https://youtube.com/@gridsound" } ),
			$.$linkExt( { title: "Facebook", class: "gsuiIcon", "data-icon": "br-facebook", href: "https://facebook.com/gridsound" } ),
			$.$linkExt( { title: "CodePen",  class: "gsuiIcon", "data-icon": "br-codepen",  href: "https://codepen.io/gridsound" } ),
			$.$linkExt( { title: "Discord",  class: "gsuiIcon", "data-icon": "br-discord",  href: "https://discord.gg/NUYxHAg" } ),
		),
	)
);
