"use strict";

GSUsetTemplate( "gsui-daw", () => [
	GSUcreateDiv( { class: "gsuiDAW-head" },
		GSUcreateDiv( { class: "gsuiDAW-area gsuiDAW-areaUser" },
			GSUcreateElement( "gsui-titleuser" ),
		),
		GSUcreateDiv( { class: "gsuiDAW-area gsuiDAW-areaCtrl" },
			GSUcreateDiv( { class: "gsuiDAW-volume", title: "Main app volume (this will not affect the rendering)" },
				GSUcreateElement( "gsui-slider", { "data-action": "volume", type: "linear-y", min: 0, max: 1, step: .01, "mousemove-size": 150 } ),
			),
			GSUcreateDiv( { class: "gsuiDAW-btns gsuiDAW-playPauseStop" },
				GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-focusBtn", "data-action": "focusSwitch", "data-dir": "up", title: "Toggle focus between the composition and piano windows" },
					GSUcreateSpan(),
					GSUcreateSpan(),
				),
				GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "play",  icon: "play" } ),
				GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "stop",  icon: "stop" } ),
				GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "reset", icon: "sync", title: "Restart the audio engine" } ),
			),
			GSUcreateDiv( { class: "gsuiDAW-btns gsuiDAW-history" },
				GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "undo", icon: "undo", title: "Undo the previous action" } ),
				GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "redo", icon: "redo", title: "Redo the last action" } ),
			),
			GSUcreateElement( "gsui-clock" ),
			GSUcreateElement( "gsui-tempo" ),
		),
		GSUcreateDiv( { class: "gsuiDAW-area gsuiDAW-areaTime" },
			GSUcreateElement( "gsui-slider", { "data-action": "currentTime", type: "linear-x", min: 0, step: .01 } ),
		),
		GSUcreateDiv( { class: "gsuiDAW-area gsuiDAW-areaVisu" },
			GSUcreateElement( "gsui-analyser-hz", { resolution: 140 } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-btnBg gsuiDAW-btnColor", "data-action": "export",   icon: "export",   title: "Export the composition" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-btnBg",                  "data-action": "settings", icon: "settings", title: "Settings" } ),
		),
		GSUcreateDiv( { class: "gsuiDAW-area gsuiDAW-areaWins gsuiDAW-btns" },
			GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "window", icon: "folder-tree", "data-win": "patterns",    title: "Open/close the patterns panel", "data-open": true } ),
			GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "window", icon: "mixer",       "data-win": "mixer",       title: "Open/close the mixer window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "window", icon: "music",       "data-win": "composition", title: "Open/close the composition window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "window", icon: "oscillator",  "data-win": "synth",       title: "Open/close the synthesizer window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "window", icon: "drums",       "data-win": "drums",       title: "Open/close the drums window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "window", icon: "keys",        "data-win": "keys",        title: "Open/close the piano window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn", "data-action": "window", icon: "slices",      "data-win": "slices",      title: "Open/close the slicer window" } ),
		),
		GSUcreateDiv( { class: "gsuiDAW-area gsuiDAW-areaHelp" },
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-btnBg",                  "data-action": "help",  icon: "help",  title: "Toggle help links" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-btnBg gsuiDAW-btnColor", "data-action": "about", icon: "about", title: "About" } ),
		),
		GSUcreateDiv( { class: "gsuiDAW-area gsuiDAW-areaVers" },
			GSUcreateAExt( { class: "gsuiDAW-btn gsuiDAW-version", "data-action": "version", title: "Changelog", href: "https://github.com/gridsound/daw/wiki/changelog" },
				GSUcreateSpan( { class: "gsuiDAW-version-number" } ),
				GSUcreateIcon( { icon: "changelog" } ),
			),
		),
	),
	GSUcreateElement( "gsui-panels", { class: "gsuiDAW-body", dir: "x" },
		GSUcreateDiv( { class: "gsuiDAW-resources" },
			GSUcreateDiv( { class: "gsuiDAW-libraries" } ),
			GSUcreateDiv( { class: "gsuiDAW-patterns" } ),
		),
		GSUcreateDiv( { class: "gsuiDAW-windows" },
			GSUcreateElement( "gsui-windows" ),
		),
	),
] );
