"use strict";

GSUsetTemplate( "gsui-daw", () => [
	GSUcreateElement( "div", { class: "gsuiDAW-head" },
		GSUcreateElement( "div", { class: "gsuiDAW-area gsuiDAW-areaUser" },
			GSUcreateElement( "span", { class: "gsuiDAW-title" }, "GridSound" ),
			GSUcreateElement( "a",    { class: "gsuiDAW-btn", "data-action": "profile", href: true, title: "Cloud profile", target: "_blank", rel: "noopener" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "login",  "data-icon": "profile", title: "Login to GridSound" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "logout", "data-icon": "logout",  title: "Logout" } ),
			GSUcreateElement( "div", { class: "gsuiDAW-cmps" },
				GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-dropdown-btn gsuiDAW-btnColor gsuiIcon", "data-action": "cmps", "data-icon": "musics", title: "Create cloud/local compositions" } ),
				GSUgetTemplate( "gsui-daw-cmps" ),
				GSUcreateElement( "div", { class: "gsuiDAW-dropdown-backdrop" } ),
			),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-area gsuiDAW-areaSave gsuiDAW-btns" },
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-btnColor gsuiDAW-currCmp-saveBtn gsuiIcon", "data-action": "cmp-save", title: "Save composition" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-currCmp-editBtn", "data-action": "cmp-rename", title: "Edit composition's title" },
				GSUcreateElement( "i",    { class: "gsuiDAW-currCmp-localIcon gsuiIcon" } ),
				GSUcreateElement( "span", { class: "gsuiDAW-currCmp-name" } ),
				GSUcreateElement( "i",    { class: "gsuiDAW-currCmp-editIcon gsuiIcon", "data-icon": "pen" } ),
				GSUcreateElement( "span", { class: "gsuiDAW-currCmp-dur" } ),
			),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-area gsuiDAW-areaCtrl" },
			GSUcreateElement( "div", { class: "gsuiDAW-volume", title: "Main app volume (this will not affect the rendering)" },
				GSUcreateElement( "gsui-slider", { "data-action": "volume", type: "linear-y", min: 0, max: 1, step: .01, "mousemove-size": 150 } ),
			),
			GSUcreateElement( "div", { class: "gsuiDAW-btns gsuiDAW-playPauseStop" },
				GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-focusBtn", "data-action": "focusSwitch", "data-dir": "up", title: "Toggle focus between the composition and piano windows" },
					GSUcreateElement( "span" ),
					GSUcreateElement( "span" ),
				),
				GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "play",  "data-icon": "play" } ),
				GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "stop",  "data-icon": "stop" } ),
				GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "reset", "data-icon": "sync", title: "Restart the audio engine" } ),
			),
			GSUcreateElement( "gsui-clock" ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-tempo", "data-action": "tempo", title: "Edit the time signature and BPM" },
				GSUcreateElement( "div", { class: "gsuiDAW-tempo-timeDivision" },
					GSUcreateElement( "span", { class: "gsuiDAW-tempo-beatsPerMeasure" } ),
					GSUcreateElement( "span", { class: "gsuiDAW-tempo-stepsPerBeat" } ),
				),
				GSUcreateElement( "span", { class: "gsuiDAW-tempo-bpm" } ),
			),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-area gsuiDAW-areaTime" },
			GSUcreateElement( "gsui-slider", { "data-action": "currentTime", type: "linear-x", min: 0, step: .01 } ),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-area gsuiDAW-areaHist" },
			GSUcreateElement( "div", { class: "gsuiDAW-btns gsuiDAW-history" },
				GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon",                      "data-action": "undo",     "data-icon": "undo",       title: "Undo the previous action" } ),
				GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon",                      "data-action": "redo",     "data-icon": "redo",       title: "Redo the last action" } ),
				GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-dropdown-btn gsuiIcon", "data-action": "undoMore", "data-icon": "caret-down", title: "Show the actions list" } ),
				GSUgetTemplate( "gsui-daw-history" ),
				GSUcreateElement( "div", { class: "gsuiDAW-dropdown-backdrop" } ),
			),
			GSUcreateElement( "gsui-spectrum" ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-btnBg gsuiDAW-btnColor gsuiIcon", "data-action": "export",   "data-icon": "export",   title: "Export the composition" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-btnBg gsuiIcon",                  "data-action": "settings", "data-icon": "settings", title: "Settings" } ),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-area gsuiDAW-areaWins gsuiDAW-btns" },
			GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "window", "data-icon": "folder-tree", "data-win": "patterns", title: "Open/close the patterns panel", "data-open": true } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "window", "data-icon": "mixer",       "data-win": "mixer",    title: "Open/close the mixer window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "window", "data-icon": "music",       "data-win": "main",     title: "Open/close the composition window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "window", "data-icon": "oscillator",  "data-win": "synth",    title: "Open/close the synthesizer window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "window", "data-icon": "drums",       "data-win": "drums",    title: "Open/close the drums window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "window", "data-icon": "keys",        "data-win": "piano",    title: "Open/close the piano window" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiIcon", "data-action": "window", "data-icon": "slices",      "data-win": "slicer",   title: "Open/close the slices window" } ),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-area gsuiDAW-areaHelp" },
			GSUcreateElement( "a",      { class: "gsuiDAW-btn gsuiDAW-btnBg gsuiIcon",                  "data-action": "help", "data-icon": "help", title: "Help", href: "https://github.com/gridsound/daw/wiki/help", target: "_blank", rel: "noopener" } ),
			GSUcreateButton( { class: "gsuiDAW-btn gsuiDAW-btnBg gsuiIcon gsuiDAW-btnColor", "data-action": "about", "data-icon": "about", title: "About" } ),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-area gsuiDAW-areaVers" },
			GSUcreateElement( "a", { class: "gsuiDAW-btn gsuiDAW-version", "data-action": "version", title: "Access older versions", href: "https://github.com/gridsound/daw/wiki/versions", target: "_blank", rel: "noopener" } ),
			GSUcreateElement( "a", { class: "gsuiDAW-btn gsuiDAW-changelog gsuiIcon", "data-icon": "changelog", title: "Changelog", href: "https://github.com/gridsound/daw/wiki/changelog", target: "_blank", rel: "noopener" } ),
		),
	),
	GSUcreateElement( "gsui-panels", { class: "gsuiDAW-body", dir: "x" },
		GSUcreateElement( "div", { class: "gsuiDAW-resources" },
			GSUcreateElement( "div", { class: "gsuiDAW-libraries" } ),
			GSUcreateElement( "div", { class: "gsuiDAW-patterns" } ),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-windows" },
			GSUcreateElement( "gsui-windows" ),
		),
	),
] );

GSUsetTemplate( "gsui-daw-cmps", () =>
	GSUcreateElement( "div", { class: "gsuiDAW-dropdown", tabindex: 0 },
		GSUcreateElement( "div", { class: "gsuiDAW-dropdown-head", "data-list": "local" },
			GSUcreateElement( "i", { class: "gsuiDAW-dropdown-icon gsuiIcon", "data-icon": "local" } ),
			GSUcreateElement( "span", { class: "gsuiDAW-dropdown-title" }, "local" ),
			GSUgetTemplate( "gsui-daw-cmps-btn", { action: "localNewCmp", icon: "plus", text: "new", title: "Create a new composition on this computer" } ),
			GSUgetTemplate( "gsui-daw-cmps-btn", { action: "localOpenCmp", icon: "folder-open", text: "open", title: "Open a composition on this computer" } ),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-dropdown-head", "data-list": "cloud" },
			GSUcreateElement( "i", { class: "gsuiDAW-dropdown-icon gsuiIcon", "data-icon": "cloud" } ),
			GSUcreateElement( "span", { class: "gsuiDAW-dropdown-title" }, "cloud" ),
			GSUgetTemplate( "gsui-daw-cmps-btn", { action: "cloudNewCmp", icon: "plus", text: "new", title: "Create a new composition on your cloud profile" } ),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-dropdown-list", "data-list": "local" },
			GSUcreateElement( "div", { class: "gsuiDAW-dropdown-placeholder" },
				GSUcreateElement( "span", null, "there is no local composition here" ),
			),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-dropdown-list", "data-list": "cloud" },
			GSUcreateElement( "div", { class: "gsuiDAW-dropdown-placeholder" },
				GSUcreateElement( "span", null, "you don't have any cloud composition yet" ),
				GSUcreateElement( "span", null, "you are not connected" ),
			),
		),
	)
);

GSUsetTemplate( "gsui-daw-cmps-btn", ( { action, title, icon, text } ) =>
	GSUcreateButton( { class: "gsuiDAW-cmps-btn", "data-action": action, title },
		GSUcreateElement( "i", { class: "gsuiDAW-cmps-btn-icon gsuiIcon", "data-icon": icon } ),
		GSUcreateElement( "span", { class: "gsuiDAW-cmps-btn-text" }, text ),
	)
);

GSUsetTemplate( "gsui-daw-cmp", ( { id, saveMode } ) =>
	GSUcreateElement( "div", { class: "gsuiDAW-cmp", "data-id": id, draggable: "true", tabindex: 0 },
		GSUcreateButton( { class: "gsuiDAW-cmp-btn gsuiIcon", "data-action": "cmp-save", "data-icon": saveMode === "local" ? "save" : "upload" } ),
		GSUcreateElement( "a", { href: true, class: "gsuiDAW-cmp-info", "data-action": "cmp-open" },
			GSUcreateElement( "div", { class: "gsuiDAW-cmp-name" } ),
			GSUcreateElement( "div", null,
				GSUcreateElement( "span", { class: "gsuiDAW-cmp-duration-wrap" },
					GSUcreateElement( "i", { class: "gsuiIcon", "data-icon": "clock" } ),
					GSUcreateElement( "span", { class: "gsuiDAW-cmp-duration" } ),
				),
				GSUcreateElement( "span", { class: "gsuiDAW-cmp-bpm-wrap" },
					GSUcreateElement( "i", { class: "gsuiIcon", "data-icon": "speed" } ),
					GSUcreateElement( "span", { class: "gsuiDAW-cmp-bpm" } ),
				),
			),
		),
		GSUcreateElement( "a", { href: true, class: "gsuiDAW-cmp-btn gsuiDAW-cmp-btn-light gsuiIcon", "data-action": "cmp-json",   "data-icon": "file-export", title: "Export to JSON file" } ),
		GSUcreateButton( { class: "gsuiDAW-cmp-btn gsuiDAW-cmp-btn-light gsuiIcon", "data-action": "cmp-delete", "data-icon": "minus-oct", title: "Delete" } ),
	)
);

GSUsetTemplate( "gsui-daw-history", () =>
	GSUcreateElement( "div", { class: "gsuiDAW-dropdown", tabindex: 0 },
		GSUcreateElement( "div", { class: "gsuiDAW-dropdown-head" },
			GSUcreateElement( "i", { class: "gsuiDAW-dropdown-icon gsuiIcon", "data-icon": "history" } ),
			GSUcreateElement( "span", { class: "gsuiDAW-dropdown-title" }, "history" ),
		),
		GSUcreateElement( "div", { class: "gsuiDAW-dropdown-list" },
			GSUcreateElement( "div", { class: "gsuiDAW-dropdown-placeholder" },
				GSUcreateElement( "span", null, "there is nothing to undo" ),
			),
		),
	)
);

GSUsetTemplate( "gsui-daw-history-action", ( { icon, desc, index } ) =>
	GSUcreateElement( "div", { class: "gsuiDAW-history-action", "data-action": "historyAction", "data-index": index, title: desc },
		GSUcreateElement( "i", { class: "gsuiDAW-history-action-icon gsuiIcon", "data-icon": icon } ),
		GSUcreateElement( "span", { class: "gsuiDAW-history-action-text" }, desc ),
	)
);
