"use strict";

GSUI.setTemplate( "gsui-daw-popup-settings", () =>
	GSUI.createElem( "div", { class: "gsuiDAW-popup-settings" },
		GSUI.createElem( "fieldset", null,
			GSUI.createElem( "legend", null, "Audio" ),
			GSUI.createElem( "div", { class: "gsuiPopup-row" },
				GSUI.createElem( "div", { class: "gsuiPopup-row-title" }, "Feedback sample rate" ),
				GSUI.createElem( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElem( "select", { name: "sampleRate" },
						GSUI.createElem( "option", { value: 8000 }, "8 kHz" ),
						GSUI.createElem( "option", { value: 11025 }, "11.025 kHz" ),
						GSUI.createElem( "option", { value: 12000 }, "12 kHz" ),
						GSUI.createElem( "option", { value: 22050 }, "22.05 kHz" ),
						GSUI.createElem( "option", { value: 24000 }, "24 kHz" ),
						GSUI.createElem( "option", { value: 44100 }, "44.1 kHz" ),
						GSUI.createElem( "option", { value: 48000, style: "font-weight:bold" }, "48 kHz" ),
						GSUI.createElem( "option", { value: 88200 }, "88.2 kHz" ),
						GSUI.createElem( "option", { value: 96000 }, "96 kHz" ),
					),
				),
			),
		),
		GSUI.createElem( "fieldset", null,
			GSUI.createElem( "legend", null, "UI refresh rate" ),
			GSUI.createElem( "div", { class: "gsuiPopup-row" },
				GSUI.createElem( "div", { class: "gsuiPopup-row-title" }, "Auto" ),
				GSUI.createElem( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElem( "label", null,
						GSUI.createElem( "input", { name: "uiRate", type: "radio", value: "auto" } ),
						GSUI.createElem( "span", { class: "gsuiDAW-uiRateFps" }, 60 ),
					),
				),
			),
			GSUI.createElem( "div", { class: "gsuiPopup-row" },
				GSUI.createElem( "div", { class: "gsuiPopup-row-title" }, "Manual" ),
				GSUI.createElem( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElem( "label", null,
						GSUI.createElem( "input", { name: "uiRate", type: "radio", value: "manual" } ),
						GSUI.createElem( "span", { class: "gsuiDAW-uiRateFps" }, 40 ),
					),
					GSUI.createElem( "input", { name: "uiRateFPS", type: "range", step: 1, min: 5, max: 40, value: 40 } ),
				),
			),
		),
		GSUI.createElem( "fieldset", null,
			GSUI.createElem( "legend", null, "Windows" ),
			GSUI.createElem( "div", { class: "gsuiPopup-row" },
				GSUI.createElem( "div", { class: "gsuiPopup-row-title" }, "Move/resize mode" ),
				GSUI.createElem( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElem( "label", null,
						GSUI.createElem( "input", { name: "windowsLowGraphics", type: "checkbox" } ),
						GSUI.createElem( "span", null, "low graphic" ),
					),
				),
			),
		),
		GSUI.createElem( "fieldset", null,
			GSUI.createElem( "legend", null, "Timeline" ),
			GSUI.createElem( "div", { class: "gsuiPopup-row" },
				GSUI.createElem( "div", { class: "gsuiPopup-row-title" }, "Numbering measures starting at" ),
				GSUI.createElem( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElem( "select", { name: "timelineNumbering" },
						GSUI.createElem( "option", { value: 0 }, 0 ),
						GSUI.createElem( "option", { value: 1 }, 1 ),
					),
				),
			),
		),
	)
);
