"use strict";

GSUsetTemplate( "gsui-wave-edit", () => [
	GSUcreateSpan( { class: "gsuiWaveEdit-head" },
		GSUcreateButton( { class: "gsuiWaveEdit-back gsuiIcon", "data-action": "back", "data-icon": "arrow-left", title: "Save and close wave edition" } ),
		GSUcreateSpan( { class: "gsuiWaveEdit-title", inert: true }, "wave-edition" ),
		GSUcreateElement( "gsui-help-link", { page: "synth-wave-edition" } ),
	),
	GSUcreateDiv( { class: "gsuiWaveEdit-body" },
		GSUcreateDiv( { class: "gsuiWaveEdit-body-graph" },
			GSUcreateElement( "gsui-wavetable-graph" ),
		),
		GSUcreateDiv( { class: "gsuiWaveEdit-body-waves" },
			GSUcreateDiv( { class: "gsuiWaveEdit-graph" },
				GSUcreateElement( "gsui-dotline", { beatlines: true, viewbox: "0 -1 1 1", xstep: 1 / 100, ystep: 1 / 50 } ),
			),
			GSUcreateDiv( { class: "gsuiWaveEdit-waves-wrap" },
				GSUcreateDiv( { class: "gsuiWaveEdit-waves" } ),
			),
		),
	),
	GSUcreateDiv( { class: "gsuiWaveEdit-wtpos" },
		GSUcreateDiv( { class: "gsuiWaveEdit-wtpos-head" },
			GSUcreateDiv( { class: "gsuiWaveEdit-wtposCurves" },
				GSUnewArray( 10, i =>
					GSUcreateDiv( { class: "gsuiWaveEdit-wtposCurve", "data-id": i },
						GSUcreateElement( "gsui-dotlinesvg", { inert: true } ),
					) ),
			),
			GSUcreateDiv( { class: "gsuiWaveEdit-wtposCurve-dur" },
				GSUcreateDiv( { class: "gsuiWaveEdit-wtposCurve-dur-body" },
					GSUcreateSpan( { inert: true }, "duration" ),
					GSUcreateElement( "gsui-slider", { type: "linear-x", min: 1, max: 8, step: 1, "mousemove-size": 300 } ),
				),
				GSUcreateElement( "b", { inert: true }, 1 ),
			),
		),
		GSUcreateDiv( { class: "gsuiWaveEdit-wtpos-graph" },
			GSUcreateDiv( { class: "gsuiWaveEdit-wtpos-waves" } ),
			GSUcreateElement( "gsui-beatlines" ),
			GSUcreateElement( "gsui-dotline", { viewbox: "0 0 1 1", xstep: 1 / 100, ystep: 1 / 100 } ),
		),
	),
] );

GSUsetTemplate( "gsui-wave-edit-wavestep", ( id, ind ) =>
	GSUcreateDiv( { class: "gsuiWaveEdit-wavestep", "data-id": id, "data-index": ind },
		GSUcreateElement( "gsui-dotlinesvg", { "data-action": "select" } ),
		GSUcreateDiv( { class: "gsuiWaveEdit-wavestep-head", "data-action": "select" },
			GSUcreateSpan( { class: "gsuiWaveEdit-wavestep-num", inert: true } ),
			GSUcreateDiv( { class: "gsuiWaveEdit-wavestep-btn gsuiIcon", "data-action": "clone", "data-icon": "clone", title: "Clone this wave" } ),
			GSUcreateDiv( { class: "gsuiWaveEdit-wavestep-btn gsuiIcon", "data-action": "remove", "data-icon": "close", title: "Remove this wave" } ),
		),
	),
);
