"use strict";

$.$setTemplate( "gsui-wave-editor", () => {
	const popId = GSUuuid();

	return $.$flex( { class: "gsuiWaveEditor-in", x: true, f1: true },
		$.$flex( { class: "gsuiWaveEditor-menu", y: true, g6: true },
			$.$div( { class: "gsuiWaveEditor-waveletBrowser-pop", id: popId, popover: true } ),
			$.$button( { class: "gsuiWaveEditor-waveBtn", popovertarget: popId },
				$.$icon( { icon: "wave-tri" } ),
				$.$icon( { icon: "list" } ),
			),
			$.$elem( "gs-label-s", null, "symmetry" ),
			$.$button( { class: "gsuiWaveEditor-symmetry", "data-action": "symmetry", "data-tooltip": GSTX.$waveEditor_toggleSymm },
				$.$icon( { icon: "arrows-h2" } ),
				$.$icon( { icon: "radio-btn-checked" } ),
			),
			$.$elem( "gs-label-s", null, "tools" ),
			$.$flex( { class: "gsuiWaveEditor-tools", x: true },
				$.$getTemplate( "gsui-wave-editor-tool-btn", "goUp",     [ [ 2, 8 ], [ 8,   2    ] ] ),
				$.$getTemplate( "gsui-wave-editor-tool-btn", "goDown",   [ [ 2, 2 ], [ 8,   8    ] ] ),
				$.$getTemplate( "gsui-wave-editor-tool-btn", "stayUp",   [ [ 2, 3 ], [ 8,   3    ] ] ),
				$.$getTemplate( "gsui-wave-editor-tool-btn", "stayDown", [ [ 2, 7 ], [ 8,   7    ] ] ),
				$.$getTemplate( "gsui-wave-editor-tool-btn", "hillUp",   [ [ 2, 8 ], [ 3,   4    ], [ 4,   2.5  ], [ 5,   2    ], [ 6,   2.5  ], [ 7, 4 ], [ 8, 8   ] ] ),
				$.$getTemplate( "gsui-wave-editor-tool-btn", "hillDown", [ [ 2, 2 ], [ 3,   6    ], [ 4,   7.5  ], [ 5,   8    ], [ 6,   7.5  ], [ 7, 6 ], [ 8, 2   ] ] ),
				$.$getTemplate( "gsui-wave-editor-tool-btn", "sineUp",   [ [ 2, 5 ], [ 3,   2.5  ], [ 4,   2    ], [ 4.5, 2.5  ], [ 5.5, 7.5  ], [ 6, 8 ], [ 7, 7.5 ], [ 8, 5 ] ] ),
				$.$getTemplate( "gsui-wave-editor-tool-btn", "sineDown", [ [ 2, 5 ], [ 3,   7.5  ], [ 4,   8    ], [ 4.5, 7.5  ], [ 5.5, 2.5  ], [ 6, 2 ], [ 7, 2.5 ], [ 8, 5 ] ] ),
				$.$getTemplate( "gsui-wave-editor-tool-btn", "easeUp",   [ [ 2, 8 ], [ 3.5, 7.75 ], [ 4.5, 7.25 ], [ 5.5, 2.75 ], [ 6.5, 2.25 ], [ 8, 2 ] ] ),
				$.$getTemplate( "gsui-wave-editor-tool-btn", "easeDown", [ [ 2, 2 ], [ 3.5, 2.25 ], [ 4.5, 2.75 ], [ 5.5, 7.25 ], [ 6.5, 7.75 ], [ 8, 8 ] ] ),
			),
			$.$flex( { y: true, g6: true },
				$.$elem( "gs-label-s", null, "mirror" ),
				$.$flex( { class: "gsuiWaveEditor-mirror", x: true, g4: true },
					$.$button( { "data-action": "mirror", "data-dir": "x" },
						$.$icon( { icon: "mirror-x" } ),
					),
					$.$elem( "gsui-slider", { "data-action": "mirror-x", type: "linear-x", min: -6, max: 4, step: .001, "mousemove-size": 1200 } ),
				),
				$.$flex( { class: "gsuiWaveEditor-mirror", x: true, g4: true },
					$.$button( { "data-action": "mirror", "data-dir": "y" },
						$.$icon( { icon: "mirror-y" } ),
					),
					$.$elem( "gsui-slider", { "data-action": "mirror-y", type: "linear-x", min: -6, max: 4, step: .001, "mousemove-size": 1200 } ),
				),
				$.$flex( { class: "gsuiWaveEditor-phase", y: true, g6: true },
					$.$elem( "gs-label-s", null, "phase" ),
					$.$elem( "gsui-slider", { "data-action": "phase", type: "linear-x", min: -1, max: 1, step: .001, "mousemove-size": 800 } ),
				),
				$.$elem( "gs-label-s", null, "normalize" ),
				$.$button( { class: "gsuiWaveEditor-normalize", "data-action": "normalize-y" },
					$.$icon( { icon: "normalize-y" } ),
					$.$icon( { icon: "check" } ),
				),
			),
			$.$flex( { class: "gsuiWaveEditor-div", y: true, g6: true },
				$.$elem( "gs-label-s", null, "grid-div" ),
				$.$getTemplate( "gsui-wave-editor-div", "x" ),
				$.$getTemplate( "gsui-wave-editor-div", "y" ),
			),
		),
		$.$flex( { class: "gsuiWaveEditor-wave", x: true, f1: true },
			$.$elem( "gsui-beatlines", { dir: "x", timedivision: "1/1", color: "#fff" } ),
			$.$elem( "gsui-beatlines", { dir: "y", timedivision: "1/1", color: "#fff", vertical: true } ),
			$.$elem( "gsui-periodicwave" ),
			$.$div( { class: "gsuiWaveEditor-wave-hover-square", inert: true } ),
		),
	);
} );

$.$setTemplate( "gsui-wave-editor-tool-btn", ( tool, pts ) =>
	$.$button( { "data-action": "tool", "data-tool": tool },
		$.$elem( "svg", { viewBox: "0 0 10 10", preserveAspectRatio: "none", inert: true },
			$.$elem( "polyline", { points: pts.join( " " ) } ),
		),
	),
);

$.$setTemplate( "gsui-wave-editor-div", dir =>
	$.$flex( { dir, y: true, xcenter: true, g2: true },
		$.$flex( { x: true, ycenter: true, g6: true },
			$.$span(),
			$.$icon( { icon: dir === "x" ? "arrows-h" : "arrows-v" } ),
		),
		$.$elem( "gsui-slider", { "data-action": `div-${ dir }`, type: "linear-x", min: 1, max: 64, step: 1, "mousemove-size": 2000 } ),
	),
);
