"use strict";

$.$setTemplate( "gsui-channel", () => [
	$.$button( { "data-action": "rename", "data-tooltip": GSTX.$channel_rename },
		$.$bold( { inert: true } ),
		$.$span( { inert: true } ),
	),
	$.$button( { "data-action": "delete", icon: "close", "data-tooltip": GSTX.$channel_remove } ),
	$.$elem( "gsui-channel-analyser", { "data-action": "select" },
		$.$elem( "gsui-analyser-hist", { inert: true } ),
		$.$elem( "gsui-channel-effects" ),
	),
	$.$elem( "gsui-toggle", { "data-tooltip": GSTX.$channel_mute } ),
	$.$elem( "gsui-channel-pan", null,
		$.$elem( "gsui-slider", { type: "circular", min: -1, max: 1, step: .02, "mousemove-size": 800, "stroke-width": 3, "data-prop": "pan", defaultValue: 0, "data-tooltip": GSTX.$channel_pan } ),
	),
	$.$elem( "gsui-channel-gain", null,
		$.$elem( "gsui-slider", { type: "linear-y", min: 0, max: 1, step: .01, "mousemove-size": 400, "data-prop": "gain", defaultValue: 1, "data-tooltip": GSTX.$channel_gain } ),
	),
	$.$button( { "data-action": "connect" },
		$.$icon( { icon: "caret-up" } ),
		$.$icon( { icon: "caret-up" } ),
	),
	$.$elem( "gsui-channel-grip", null,
		$.$icon( { icon: "grip-h" } ),
	),
] );
