"use strict";

GSUsetTemplate( "gsui-fx-reverb", () => [
	GSUcreateDiv( { class: "gsuiEffect-param-row", "data-prop": "dry" },
		GSUcreateLabel( null, "dry" ),
		GSUcreateElement( "output" ),
		GSUcreateElement( "gsui-slider", { type: "linear-x", min: 0, max: 1, step: .01 } ),
	),
	GSUcreateDiv( { class: "gsuiEffect-param-row", "data-prop": "wet" },
		GSUcreateLabel( null, "wet" ),
		GSUcreateElement( "output" ),
		GSUcreateElement( "gsui-slider", { type: "linear-x", min: 0, max: 10, step: .01 } ),
	),
	GSUcreateDiv( { class: "gsuiEffect-param-row", "data-prop": "delay" },
		GSUcreateLabel( null, "delay" ),
		GSUcreateElement( "output" ),
		GSUcreateElement( "gsui-slider", { type: "linear-x", min: 0, max: 2, step: .01 } ),
	),
	GSUcreateDiv( { class: "gsuiEffect-param-row", "data-prop": "fadein" },
		GSUcreateLabel( null, "fadeIn" ),
		GSUcreateElement( "output" ),
		GSUcreateElement( "gsui-slider", { type: "linear-x", min: 0, max: 2, step: .01 } ),
	),
	GSUcreateDiv( { class: "gsuiEffect-param-row", "data-prop": "decay" },
		GSUcreateLabel( null, "decay" ),
		GSUcreateElement( "output" ),
		GSUcreateElement( "gsui-slider", { type: "linear-x", min: 0, max: 2, step: .01 } ),
	),
	GSUcreateDiv( { class: "gsuiFxReverb-graph" },
		GSUcreateElement( "gsui-beatlines", { timedivision: "4/4", color: "#fff" } ),
		GSUcreateDiv( { class: "gsuiFxReverb-graph-wet" } ),
		GSUcreateDiv( { class: "gsuiFxReverb-graph-dry" } ),
	),
] );
