"use strict";

GSUsetTemplate( "gsui-titleuser", () => [
	GSUcreateDiv( { class: "gsuiTitleUser-top" },
		GSUcreateSpan( { class: "gsuiTitleUser-gs", inert: true } ),
		GSUcreateButton( { class: "gsuiTitleUser-login", icon: "profile", title: "Login / connection" } ),
		GSUcreateAExt( { class: "gsuiTitleUser-user", title: "Go to your profile" },
			GSUcreateDiv( { class: "gsuiTitleUser-avatar", inert: true } ),
			GSUcreateDiv( { class: "gsuiTitleUser-names", inert: true },
				GSUcreateSpan( { class: "gsuiTitleUser-name" } ),
				GSUcreateSpan( { class: "gsuiTitleUser-username" } ),
			),
		),
		GSUcreateButton( { class: "gsuiTitleUser-logout", icon: "logout", title: "Logout / disconnect" } ),
	),
	GSUcreateDiv( { class: "gsuiTitleUser-cmp" },
		GSUcreateButton( { class: "gsuiTitleUser-save", icon: "upload", title: "Save composition" } ),
		GSUcreateSpan(   { class: "gsuiTitleUser-justSaved", inert: true }, "SAVED" ),
		GSUcreateButton( { class: "gsuiTitleUser-rename", title: "Edit composition's title" },
			GSUcreateSpan( { class: "gsuiTitleUser-cmpName", inert: true } ),
			GSUcreateIcon( { class: "gsuiTitleUser-cmpEditIcon", icon: "pen" } ),
			GSUcreateSpan( { class: "gsuiTitleUser-cmpDur", inert: true } ),
		),
		GSUcreateInput( { class: "gsuiTitleUser-rename-inp", type: "text", placeholder: "Untitled..." } ),
	),
] );

GSUsetTemplate( "gsui-titleuser-popup", () =>
	GSUcreateDiv( { class: "gsuiTitleUser-popup" },
		GSUcreateElement( "fieldset", null,
			GSUcreateElement( "legend", null, "Sign in" ),
			GSUcreateDiv( { class: "gsuiPopup-row" },
				GSUcreateDiv( { class: "gsuiPopup-row-title" },
					GSUcreateSpan( null, "Username" ),
					GSUcreateElement( "br" ),
					GSUcreateElement( "small", null, "(or email)" ),
				),
				GSUcreateDiv( { class: "gsuiPopup-row-values" },
					GSUcreateInput( { class: "gsuiPopup-inputText", required: true, name: "email", type: "text" } ),
				),
			),
			GSUcreateDiv( { class: "gsuiPopup-row" },
				GSUcreateDiv( { class: "gsuiPopup-row-title" }, "Password" ),
				GSUcreateDiv( { class: "gsuiPopup-row-values" },
					GSUcreateInput( { class: "gsuiPopup-inputText", required: true, name: "password", type: "password" } ),
				),
			),
			GSUcreateDiv( { class: "gsuiTitleUser-popup-error" } ),
		),
		GSUcreateAExt( { href: "https://gridsound.com/#/forgotPassword" }, "Forgot password ?" ),
		GSUcreateElement( "br" ),
		GSUcreateAExt( { href: "https://gridsound.com/#/auth" }, "Create a new account" ),
	)
);
