"use strict";

GSUsetTemplate( "gsui-titleuser", () => [
	$.$div( { class: "gsuiTitleUser-top" },
		$.$span( { class: "gsuiTitleUser-gs", inert: true } ),
		$.$button( { class: "gsuiTitleUser-login", icon: "profile", title: "Login / connection" } ),
		$.$linkExt( { class: "gsuiTitleUser-user", title: "Go to your profile" },
			$.$div( { class: "gsuiTitleUser-avatar", inert: true } ),
			$.$div( { class: "gsuiTitleUser-names", inert: true },
				$.$span( { class: "gsuiTitleUser-name" } ),
				$.$span( { class: "gsuiTitleUser-username" } ),
			),
		),
		$.$button( { class: "gsuiTitleUser-logout", icon: "logout", title: "Logout / disconnect" } ),
	),
	$.$div( { class: "gsuiTitleUser-cmp" },
		$.$button( { class: "gsuiTitleUser-save", icon: "upload", title: "Save composition" } ),
		$.$span(   { class: "gsuiTitleUser-justSaved", inert: true }, "SAVED" ),
		$.$button( { class: "gsuiTitleUser-rename", title: "Edit composition's title" },
			$.$span( { class: "gsuiTitleUser-cmpName", inert: true } ),
			$.$icon( { class: "gsuiTitleUser-cmpEditIcon", icon: "pen" } ),
			$.$span( { class: "gsuiTitleUser-cmpDur", inert: true } ),
		),
		$.$input( { class: "gsuiTitleUser-rename-inp", type: "text", placeholder: "Untitled..." } ),
	),
] );

GSUsetTemplate( "gsui-titleuser-popup", () =>
	$.$div( { class: "gsuiTitleUser-popup" },
		$.$elem( "fieldset", null,
			$.$elem( "legend", null, "Sign in" ),
			$.$div( { class: "gsuiPopup-row" },
				$.$div( { class: "gsuiPopup-row-title" },
					$.$span( null, "Username" ),
					$.$elem( "br" ),
					$.$elem( "small", null, "(or email)" ),
				),
				$.$div( { class: "gsuiPopup-row-values" },
					$.$input( { class: "gsuiPopup-inputText", required: true, name: "email", type: "text" } ),
				),
			),
			$.$div( { class: "gsuiPopup-row" },
				$.$div( { class: "gsuiPopup-row-title" }, "Password" ),
				$.$div( { class: "gsuiPopup-row-values" },
					$.$input( { class: "gsuiPopup-inputText", required: true, name: "password", type: "password" } ),
				),
			),
			$.$div( { class: "gsuiTitleUser-popup-error" } ),
		),
		$.$linkExt( { href: "https://gridsound.com/#/forgotPassword" }, "Forgot password ?" ),
		$.$elem( "br" ),
		$.$linkExt( { href: "https://gridsound.com/#/auth" }, "Create a new account" ),
	)
);
