"use strict";

$.$setTemplate( "gsui-titleuser", () => [
	$.$div( { class: "gsuiTitleUser-top" },
		$.$span( { class: "gsuiTitleUser-gs", inert: true } ),
		$.$button( { class: "gsuiTitleUser-login", icon: "profile", "data-tooltip": GSTX.$user_login } ),
		$.$linkExt( { class: "gsuiTitleUser-user", "data-tooltip": GSTX.$user_goProfile },
			$.$div( { class: "gsuiTitleUser-avatar", inert: true } ),
			$.$div( { class: "gsuiTitleUser-names", inert: true },
				$.$span( { class: "gsuiTitleUser-name" } ),
				$.$span( { class: "gsuiTitleUser-username" } ),
			),
		),
		$.$button( { class: "gsuiTitleUser-logout", icon: "logout", "data-tooltip": GSTX.$user_logout } ),
	),
	$.$div( { class: "gsuiTitleUser-cmp" },
		$.$button( { class: "gsuiTitleUser-save", icon: "upload", "data-tooltip": GSTX.$user_saveCmp } ),
		$.$span(   { class: "gsuiTitleUser-justSaved", inert: true }, "SAVED" ),
		$.$button( { class: "gsuiTitleUser-rename", "data-tooltip": GSTX.$user_renameCmp },
			$.$span( { class: "gsuiTitleUser-cmpName", inert: true } ),
			$.$icon( { class: "gsuiTitleUser-cmpEditIcon", icon: "pen" } ),
			$.$span( { class: "gsuiTitleUser-cmpDur", inert: true } ),
		),
		$.$input( { class: "gsuiTitleUser-rename-inp", type: "text", placeholder: "Untitled..." } ),
	),
] );

$.$setTemplate( "gsui-titleuser-popup", () =>
	$.$div( { class: "gsuiTitleUser-popup" },
		$.$elem( "fieldset", null,
			$.$elem( "legend", null, "Sign in" ),
			$.$div( { class: "gsuiPopup-row" },
				$.$div( { class: "gsuiPopup-row-title" },
					$.$span( null, "Username" ),
					$.$elem( "br" ),
					$.$elem( "small", null, "(or email)" ),
				),
				$.$div( { class: "gsuiPopup-row-values" },
					$.$input( { class: "gsuiPopup-inputText", required: true, name: "email", type: "text" } ),
				),
			),
			$.$div( { class: "gsuiPopup-row" },
				$.$div( { class: "gsuiPopup-row-title" }, "Password" ),
				$.$div( { class: "gsuiPopup-row-values" },
					$.$input( { class: "gsuiPopup-inputText", required: true, name: "password", type: "password" } ),
				),
			),
			$.$div( { class: "gsuiTitleUser-popup-error" } ),
		),
		$.$linkExt( { href: "https://gridsound.com/#/forgotPassword" }, GSTX.$user_passForgot ),
		$.$elem( "br" ),
		$.$linkExt( { href: "https://gridsound.com/#/auth" }, GSTX.$user_newAccount ),
	)
);
