"use strict";

GSUsetTemplate( "gsui-slicer", () => [
	GSUcreateElement( "div", { class: "gsuiSlicer-source" },
		GSUcreateElement( "div", { class: "gsuiSlicer-source-head" },
			GSUcreateElement( "i", { class: "gsuiSlicer-source-icon gsuiIcon", "data-icon": "waveform" } ),
			GSUcreateElement( "span", { class: "gsuiSlicer-source-name" } ),
		),
		GSUcreateElement( "div", { class: "gsuiSlicer-source-sample-wrap" },
			GSUcreateElement( "div", { class: "gsuiSlicer-source-sample" },
				GSUcreateElementSVG( "svg", { class: "gsuiSlicer-source-wave", viewBox: "0 0 1000 64", preserveAspectRatio: "none" },
					GSUcreateElementSVG( "polyline" ),
				),
				GSUcreateElement( "div", { class: "gsuiSlicer-currentTime gsuiSlicer-source-currentTime" } ),
			),
		),
	),
	GSUcreateElement( "div", { class: "gsuiSlicer-time" },
		GSUcreateElement( "gsui-timeline" ),
	),
	GSUcreateElement( "div", { class: "gsuiSlicer-preview" },
		GSUcreateElement( "div", { class: "gsuiSlicer-currentTime gsuiSlicer-preview-currentTime" } ),
	),
	GSUcreateElement( "div", { class: "gsuiSlicer-slices" },
		GSUcreateElement( "div", { class: "gsuiSlicer-slices-scroll" },
			GSUcreateElement( "div", { class: "gsuiSlicer-slices-in" },
				GSUcreateElement( "div", { class: "gsuiSlicer-slices-beatlinesWrap" },
					GSUcreateElement( "gsui-beatlines" ),
					GSUcreateElement( "gsui-beatlines", { vertical: true } ),
				),
				GSUcreateElement( "div", { class: "gsuiSlicer-currentTime gsuiSlicer-slices-currentTime" } ),
				GSUcreateElementSVG( "svg", { class: "gsuiSlicer-slices-line", preserveAspectRatio: "none" },
					GSUcreateElementSVG( "line" ),
				),
				GSUcreateElement( "div", { class: "gsuiSlicer-slices-wrap" } ),
			),
		),
	),
	GSUcreateElement( "div", { class: "gsuiSlicer-menu" },
		GSUcreateButton( { class: "gsuiSlicer-btn gsuiSlicer-btn-step", title: "Magnetism" },
			GSUcreateElement( "span", { class: "gsuiSlicer-btn-step-value" } ),
			GSUcreateElement( "i", { class: "gsuiIcon", "data-icon": "magnet" } ),
		),
		GSUcreateButton( { class: "gsuiSlicer-btn gsuiIcon", "data-action": "moveY", "data-icon": "hand-pointer", title: "Move slices vertically" } ),
		GSUcreateButton( { class: "gsuiSlicer-btn gsuiIcon", "data-action": "reset", "data-icon": "slices", title: "Reset slices vertically" } ),
		GSUcreateButton( { class: "gsuiSlicer-btn gsuiIcon", "data-action": "split", "data-icon": "cut", title: "Cut slices in half" } ),
		GSUcreateButton( { class: "gsuiSlicer-btn gsuiIcon", "data-action": "merge", "data-icon": "erase", title: "Merge slices together" } ),
	),
] );
