"use strict";

GSUsetTemplate( "gsui-wavetable", () => [
	GSUcreateSpan( { class: "gsuiWavetable-head" },
		GSUcreateButton( { class: "gsuiWavetable-back gsuiIcon", "data-action": "back", "data-icon": "arrow-left", title: "Save and close the wavetable edition" } ),
		GSUcreateSpan( { class: "gsuiWavetable-title", inert: true }, "wavetable editor" ),
		GSUcreateElement( "gsui-help-link", { page: "synth-wave-edition" } ),
	),
	GSUcreateDiv( { class: "gsuiWavetable-waves" },
		GSUcreateDiv( { class: "gsuiWavetable-waves-graph" },
			GSUcreateElement( "gsui-wavetable-graph" ),
		),
		GSUcreateDiv( { class: "gsuiWavetable-waves-editor" },
			GSUcreateDiv( { class: "gsuiWavetable-wave-editor" },
				GSUcreateElement( "gsui-dotline", { beatlines: true, viewbox: "0 -1 1 1", xstep: 1 / 100, ystep: 1 / 50 } ),
			),
			GSUcreateDiv( { class: "gsuiWavetable-waves-list-wrap" },
				GSUcreateDiv( { class: "gsuiWavetable-waves-list" } ),
			),
		),
	),
	GSUcreateDiv( { class: "gsuiWavetable-posCurves" },
		GSUcreateDiv( { class: "gsuiWavetable-posCurves-head" },
			GSUcreateDiv( { class: "gsuiWavetable-posCurves-list" },
				GSUnewArray( 10, i =>
					GSUcreateDiv( { class: "gsuiWavetable-posCurve", "data-id": i },
						GSUcreateDiv( { class: "gsuiWavetable-keyPreviews", inert: true } ),
						GSUcreateElement( "gsui-dotlinesvg", { inert: true } ),
					) ),
			),
			GSUcreateDiv( { class: "gsuiWavetable-posCurve-dur" },
				GSUcreateDiv( { class: "gsuiWavetable-posCurve-dur-body" },
					GSUcreateSpan( { inert: true }, "duration" ),
					GSUcreateElement( "gsui-slider", { type: "linear-x", min: 1, max: 8, step: 1, "mousemove-size": 300 } ),
				),
				GSUcreateElement( "b", { inert: true }, 1 ),
			),
		),
		GSUcreateDiv( { class: "gsuiWavetable-posCurves-graph" },
			GSUcreateDiv( { class: "gsuiWavetable-posCurves-graph-waves", inert: true } ),
			GSUcreateElement( "gsui-beatlines", { inert: true } ),
			GSUcreateElement( "gsui-dotline", { viewbox: "0 0 1 1", xstep: 1 / 100, ystep: 1 / 100 } ),
			GSUcreateDiv( { class: "gsuiWavetable-keyPreviews", inert: true } ),
		),
	),
] );

GSUsetTemplate( "gsui-wavetable-wave", ( id, ind ) =>
	GSUcreateDiv( { class: "gsuiWavetable-wave", "data-id": id, "data-index": ind },
		GSUcreateElement( "gsui-dotlinesvg", { "data-action": "select" } ),
		GSUcreateDiv( { class: "gsuiWavetable-wave-head", "data-action": "select" },
			GSUcreateSpan( { class: "gsuiWavetable-wave-num", inert: true } ),
			GSUcreateDiv( { class: "gsuiWavetable-wave-btn gsuiIcon", "data-action": "clone", "data-icon": "clone", title: "Clone this wave" } ),
			GSUcreateDiv( { class: "gsuiWavetable-wave-btn gsuiIcon", "data-action": "remove", "data-icon": "close", title: "Remove this wave" } ),
		),
	),
);
