"use strict";

GSUsetTemplate( "gsui-wavetable", () => [
	GSUcreateFlex( { class: "gsuiWavetable-head", x: true, ycenter: true, g6: true },
		GSUcreateButton( { class: "gsuiWavetable-back", "data-action": "back", icon: "arrow-left", title: "Save and close the wavetable edition" } ),
		GSUcreateSpan( { class: "gsuiWavetable-title", inert: true }, "wavetable editor" ),
		GSUcreateElement( "gsui-help-link", { page: "synth-wavetable" } ),
	),
	GSUcreateFlex( { class: "gsuiWavetable-waves", x: true, f3: true },
		GSUcreateFlex( { f1: true },
			GSUcreateElement( "gsui-wavetable-graph" ),
		),
		GSUcreateFlex( { y: true, f2: true },
			GSUcreateElement( "gsui-wave-editor" ),
			GSUcreateDiv( { class: "gsuiWavetable-waves-list" },
				GSUcreateDiv(),
			),
		),
	),
	GSUcreateFlex( { class: "gsuiWavetable-posCurves", y: true, f2: true, g6: true },
		GSUcreateFlex( { class: "gsuiWavetable-posCurves-head", x: true, g10: true },
			GSUcreateFlex( { class: "gsuiWavetable-posCurves-list", x: true, f1: true, g8: true },
				GSUnewArray( 10, i =>
					GSUcreateFlex( { class: "gsuiWavetable-posCurve", "data-id": i, f1: true },
						GSUcreateDiv( { class: "gsuiWavetable-keyPreviews", inert: true } ),
						GSUcreateElement( "gsui-dotlinesvg", { inert: true } ),
					) ),
			),
			GSUcreateFlex( { class: "gsuiWavetable-posCurve-dur", x: true, ycenter: true, g6: true },
				GSUcreateFlex( { y: true },
					GSUcreateSpan( { inert: true }, "duration" ),
					GSUcreateElement( "gsui-slider", { type: "linear-x", min: 1, max: 8, step: 1, "mousemove-size": 300 } ),
				),
				GSUcreateElement( "b", { inert: true }, 1 ),
			),
		),
		GSUcreateFlex( { f1: true, class: "gsuiWavetable-posCurves-graph" },
			GSUcreateDiv( { class: "gsuiWavetable-posCurves-graph-waves", inert: true } ),
			GSUcreateElement( "gsui-beatlines", { color: "#fff" } ),
			GSUcreateElement( "gsui-dotline", { viewbox: "0 0 1 1", xstep: 1 / 100, ystep: 1 / 100 } ),
			GSUcreateDiv( { class: "gsuiWavetable-keyPreviews", inert: true } ),
		),
	),
] );

GSUsetTemplate( "gsui-wavetable-wave", ( id, ind ) =>
	GSUcreateFlex( { class: "gsuiWavetable-wave", "data-id": id, "data-index": ind, x: true },
		GSUcreateFlex( { class: "gsuiWavetable-wave-svg", "data-action": "select", f1: true },
			GSUcreateElement( "svg", { inert: true },
				GSUcreateElement( "polyline" ),
			),
		),
		GSUcreateFlex( { class: "gsuiWavetable-wave-head", "data-action": "select", y: true, xcenter: true, ycenter: true },
			GSUcreateSpan( { class: "gsuiWavetable-wave-num", inert: true } ),
			GSUcreateDiv( { class: "gsuiWavetable-wave-btn gsuiIcon", "data-action": "clone", "data-icon": "clone", title: "Clone this wave" } ),
			GSUcreateDiv( { class: "gsuiWavetable-wave-btn gsuiIcon", "data-action": "remove", "data-icon": "close", title: "Remove this wave" } ),
		),
	),
);
