"use strict";

$.$setTemplate( "gsui-wavetable", () => [
	$.$flex( { class: "gsuiWavetable-head", x: true, ycenter: true, g6: true },
		$.$button( { class: "gsuiWavetable-back", "data-action": "back", icon: "arrow-left", title: "Save and close the wavetable edition" } ),
		$.$span( { class: "gsuiWavetable-title", inert: true }, "wavetable editor" ),
		$.$elem( "gsui-help-link", { page: "synth-wavetable" } ),
	),
	$.$flex( { class: "gsuiWavetable-waves", x: true, f3: true },
		$.$flex( { f1: true },
			$.$elem( "gsui-wavetable-graph" ),
		),
		$.$flex( { y: true, f2: true },
			$.$elem( "gsui-wave-editor" ),
			$.$div( { class: "gsuiWavetable-waves-list" },
				$.$div(),
			),
		),
	),
	$.$flex( { class: "gsuiWavetable-posCurves", y: true, f2: true, g6: true },
		$.$flex( { class: "gsuiWavetable-posCurves-head", x: true, g10: true },
			$.$flex( { class: "gsuiWavetable-posCurves-list", x: true, f1: true, g8: true },
				GSUnewArray( 10, i =>
					$.$flex( { class: "gsuiWavetable-posCurve", "data-id": i, f1: true },
						$.$div( { class: "gsuiWavetable-keyPreviews", inert: true } ),
						$.$elem( "gsui-dotlinesvg", { inert: true } ),
					) ),
			),
			$.$elem( "gsui-duration" ),
		),
		$.$flex( { f1: true, class: "gsuiWavetable-posCurves-graph" },
			$.$div( { class: "gsuiWavetable-posCurves-graph-waves", inert: true } ),
			$.$elem( "gsui-beatlines", { color: "#fff" } ),
			$.$elem( "gsui-dotline", { viewbox: "0 0 1 1", xstep: 1 / 100, ystep: 1 / 100 } ),
			$.$div( { class: "gsuiWavetable-keyPreviews", inert: true } ),
		),
	),
] );

$.$setTemplate( "gsui-wavetable-wave", ( id, ind ) =>
	$.$flex( { class: "gsuiWavetable-wave", "data-id": id, "data-index": ind, x: true },
		$.$elem( "gsui-periodicwave", { "data-action": "select" } ),
		$.$flex( { "data-action": "select", y: true, xcenter: true, ycenter: true, f1: true },
			$.$span( { inert: true } ),
			$.$button( { "data-action": "clone", icon: "clone", "data-tooltip": GSTX.$wavetable_cloneWave } ),
			$.$button( { "data-action": "remove", icon: "close", "data-tooltip": GSTX.$wavetable_removeWave } ),
		),
	),
);
