"use strict";

GSUI.setTemplate( "gsui-drumrows", () => [
	GSUI.createElem( "div", { class: "gsuiDrumrows-drop" },
		GSUI.createElem( "div", { class: "gsuiDrumrows-dropIn" },
			GSUI.createElem( "i", { class: "gsuiIcon", "data-icon": "arrow-dropdown" } ),
			GSUI.createElem( "i", { class: "gsuiIcon", "data-icon": "arrow-dropdown" } ),
			GSUI.createElem( "i", { class: "gsuiIcon", "data-icon": "arrow-dropdown" } ),
		),
	),
] );

GSUI.setTemplate( "gsui-drumrow", () =>
	GSUI.createElem( "form", { class: "gsuiDrumrow", draggable: "true" },
		GSUI.createElem( "div", { class: "gsuiDrumrow-grip" },
			GSUI.createElem( "i", { class: "gsuiIcon", "data-icon": "grip-v" } ),
		),
		GSUI.createElem( "div", { class: "gsuiDrumrow-main" },
			GSUI.createElem( "button", { type: "button", class: "gsuiIcon gsuiDrumrow-btnToggle", "data-action": "toggle", "data-icon": "toggle", title: "Toggle the drumrow (right click for solo)" } ),
			GSUI.createElem( "button", { type: "button", class: "gsuiIcon gsuiDrumrow-btnProps", "data-action": "props", "data-icon": "drumprops", title: "Expand props panel" } ),
			GSUI.createElem( "button", { type: "button", class: "gsuiIcon gsuiDrumrow-btnDelete", "data-action": "delete", "data-icon": "close", title: "Remove the drumrow" } ),
			GSUI.createElem( "span", { class: "gsuiDrumrow-name" } ),
			GSUI.createElem( "div", { class: "gsuiDrumrow-waveWrap" } ),
			GSUI.createElem( "div", { class: "gsuiDrumrow-detune", title: "pitch" },
				GSUI.createElem( "gsui-slider", { type: "linear-y", min: -12, max: 12, step: 1, "mousemove-size": 400, "data-prop": "detune" } ),
			),
			GSUI.createElem( "div", { class: "gsuiDrumrow-pan", title: "pan" },
				GSUI.createElem( "gsui-slider", { type: "linear-y", min: -1, max: 1, step: .02, "mousemove-size": 400, "data-prop": "pan" } ),
			),
			GSUI.createElem( "div", { class: "gsuiDrumrow-gain", title: "gain" },
				GSUI.createElem( "gsui-slider", { type: "linear-y", min: 0, max: 1, step: .01, "mousemove-size": 400, "data-prop": "gain" } ),
			),
		),
		GSUI.createElem( "div", { class: "gsuiDrumrow-props" },
			GSUI.createElem( "label", { class: "gsuiDrumrow-prop gsuiDrumrow-propDetune", tabindex: 0 },
				GSUI.createElem( "input", { class: "gsuiDrumrow-propRadio", type: "radio", name: "prop", value: "detune" }, "pitch" ),
				GSUI.createElem( "span", { class: "gsuiDrumrow-propSpan" }, "pitch" ),
			),
			GSUI.createElem( "label", { class: "gsuiDrumrow-prop gsuiDrumrow-propPan", tabindex: 0 },
				GSUI.createElem( "input", { class: "gsuiDrumrow-propRadio", type: "radio", name: "prop", value: "pan" }, "pan" ),
				GSUI.createElem( "span", { class: "gsuiDrumrow-propSpan" }, "pan" ),
			),
			GSUI.createElem( "label", { class: "gsuiDrumrow-prop gsuiDrumrow-propGain", tabindex: 0 },
				GSUI.createElem( "input", { class: "gsuiDrumrow-propRadio", type: "radio", name: "prop", value: "gain" }, "gain" ),
				GSUI.createElem( "span", { class: "gsuiDrumrow-propSpan" }, "gain" ),
			),
		),
		GSUI.createElem( "div", { class: "gsuiDrumrows-drop" },
			GSUI.createElem( "div", { class: "gsuiDrumrows-dropIn" },
				GSUI.createElem( "i", { class: "gsuiIcon", "data-icon": "arrow-dropdown" } ),
				GSUI.createElem( "i", { class: "gsuiIcon", "data-icon": "arrow-dropdown" } ),
				GSUI.createElem( "i", { class: "gsuiIcon", "data-icon": "arrow-dropdown" } ),
			),
		),
	)
);
