"use strict";

$.$setTemplate( "gsui-fx-filter", () => [
	$.$elem( "gsui-fx-filter-area", { a: "type" },
		$.$elem( "gs-label", null, "type" ),
		$.$div( null,
			$.$getTemplate( "gsui-fx-filter-type", "lowpass",   "M 1 4 L 12 4 L 15 8" ),
			$.$getTemplate( "gsui-fx-filter-type", "highpass",  "M 1 8 L 4 4 L 15 4" ),
			$.$getTemplate( "gsui-fx-filter-type", "bandpass",  "M 1 8 L 8 4 L 15 8" ),
			$.$getTemplate( "gsui-fx-filter-type", "lowshelf",  "M 1 8 L 4 8 L 6 4 L 15 4" ),
			$.$getTemplate( "gsui-fx-filter-type", "highshelf", "M 1 4 L 10 4 L 12 8 L 15 8" ),
			$.$getTemplate( "gsui-fx-filter-type", "peaking",   "M 1 8 L 7 8 L 8 4 L 9 8 L 15 8" ),
			$.$getTemplate( "gsui-fx-filter-type", "notch",     "M 1 4 L 7 4 L 8 8 L 9 4 L 15 4" ),
			$.$getTemplate( "gsui-fx-filter-type", "allpass",   "M 1 6 L 15 6" ),
		),
	),
	$.$elem( "gsui-fx-filter-area", { a: "graph" },
		$.$elem( "gs-label", null, "frequency" ),
		$.$div( null,
			$.$elem( "gsui-curves" ),
		),
	),
	$.$elem( "gsui-fx-filter-area", { a: "frequency" },
		$.$div( null,
			$.$elem( "gsui-slider", { type: "linear-x", min: 0, max: 1, step: .001, "data-prop": "frequency" } ),
		),
	),
	$.$elem( "gsui-fx-filter-area", { a: "gain" },
		$.$elem( "gs-label", null, "gain" ),
		$.$div( null,
			$.$elem( "gsui-slider", { type: "linear-y", min: -50, max: 50, step: .1, "mousemove-size": 400, "data-prop": "gain" } ),
		),
	),
	$.$elem( "gsui-fx-filter-area", { a: "q" },
		$.$elem( "gs-label", null, "Q" ),
		$.$div( null,
			$.$elem( "gsui-slider", { type: "circular", min: .001, max: 25, step: .001, "mousemove-size": 400, "data-prop": "Q" } ),
		),
	),
	$.$elem( "gsui-fx-filter-area", { a: "detune" },
		$.$elem( "gs-label", null, "detune" ),
		$.$div( null,
			$.$elem( "gsui-slider", { type: "circular", min: -1200, max: 1200, step: 10, "mousemove-size": 400, "data-prop": "detune" } ),
		),
	),
] );

$.$setTemplate( "gsui-fx-filter-type", ( type, d ) =>
	$.$button( { "data-type": type, "data-tooltip": type },
		$.$elem( "svg", { viewBox: "0 0 16 12" },
			$.$elem( "path", { d } ),
		),
	)
);
