"use strict";

GSUsetTemplate( "gsui-fx-waveshaper", () => [
	$.$div( { class: "gsuiFxWaveShaper-params" },
		$.$div( { class: "gsuiFxWaveShaper-symmetry" },
			$.$elem( "gsui-toggle", { off: true, "data-prop": "symmetry" } ),
			$.$elem( "gs-label", null, "symm" ),
		),
		$.$div( { class: "gsuiFxWaveShaper-oversample" },
			$.$elem( "gsui-toggle", { off: true, "data-prop": "oversample" } ),
			$.$elem( "gs-label", null, "oversmp" ),
			$.$select( { class: "gsuiEffect-param-value" },
				$.$option( { value: "2x" } ),
				$.$option( { value: "4x" } ),
			),
		),
		$.$button( { class: "gsuiFxWaveShaper-reset gsuiEffect-param-value" }, "reset" ),
	),
	$.$div( { class: "gsuiFxWaveShaper-in" },
		$.$div( { class: "gsuiFxWaveShaper-side-graph" },
			$.$div( { class: "gsuiFxWaveShaper-graph" },
				$.$elem( "svg", { class: "gsuiFxWaveShaper-graph-diag", preserveAspectRatio: "none", inert: true },
					$.$elem( "line" ),
				),
				$.$div( { class: "gsuiFxWaveShaper-graph-x", inert: true } ),
				$.$div( { class: "gsuiFxWaveShaper-graph-y", inert: true } ),
				$.$div( { class: "gsuiFxWaveShaper-graph-unit gsuiFxWaveShaper-graph-x-plus", inert: true } ),
				$.$div( { class: "gsuiFxWaveShaper-graph-unit gsuiFxWaveShaper-graph-x-minus", inert: true } ),
				$.$div( { class: "gsuiFxWaveShaper-graph-unit gsuiFxWaveShaper-graph-y-plus", inert: true } ),
				$.$div( { class: "gsuiFxWaveShaper-graph-unit gsuiFxWaveShaper-graph-y-minus", inert: true } ),
				$.$elem( "gsui-dotline", { viewbox: "-1 -1 1 1", xstep: .01, ystep: .01 } ),
			),
		),
		$.$div( { class: "gsuiFxWaveShaper-side-waves" },
			$.$elem( "svg", { class: "gsuiFxWaveShaper-waves", preserveAspectRatio: "none", inert: true },
				$.$elem( "polyline", { class: "gsuiFxWaveShaper-waveA" } ),
				$.$elem( "polyline", { class: "gsuiFxWaveShaper-waveB" } ),
			),
		),
	),
] );
