"use strict";

$.$setTemplate( "gsui-window", () => [
	$.$div( { class: "gsuiWindow-handlers" },
		$.$div( { class: "gsuiWindow-handler", "data-dir": "n" } ),
		$.$div( { class: "gsuiWindow-handler", "data-dir": "e" } ),
		$.$div( { class: "gsuiWindow-handler", "data-dir": "s" } ),
		$.$div( { class: "gsuiWindow-handler", "data-dir": "w" } ),
		$.$div( { class: "gsuiWindow-handler", "data-dir": "nw" } ),
		$.$div( { class: "gsuiWindow-handler", "data-dir": "ne" } ),
		$.$div( { class: "gsuiWindow-handler", "data-dir": "sw" } ),
		$.$div( { class: "gsuiWindow-handler", "data-dir": "se" } ),
	),
	$.$div( { class: "gsuiWindow-wrap" },
		$.$div( { class: "gsuiWindow-head" },
			$.$button( { class: "gsuiWindow-icon gsuiIcon", tabindex: -1 } ),
			$.$div( { class: "gsuiWindow-name", inert: true } ),
			$.$div( { class: "gsuiWindow-headContent" } ),
			$.$div( { class: "gsuiWindow-headBtns" },
				$.$button( { class: "gsuiWindow-headBtn", "data-action": "minimize", icon: "minimize", title: "Minimize" } ),
				$.$button( { class: "gsuiWindow-headBtn", "data-action": "restore", title: "Restore" },
					$.$icon( { icon: "restore" } ),
					$.$icon( { icon: "compress" } ),
				),
				$.$button( { class: "gsuiWindow-headBtn", "data-action": "maximize", title: "Maximize" },
					$.$icon( { icon: "maximize" } ),
					$.$icon( { icon: "expand" } ),
				),
				$.$button( { class: "gsuiWindow-headBtn", "data-action": "close", icon: "close", title: "Close" } ),
			),
		),
		$.$div( { class: "gsuiWindow-content" } ),
	),
] );
