"use strict";

GSUsetTemplate( "gsui-window", id => [
	GSUcreateDiv( { class: "gsuiWindow-handlers" },
		GSUcreateDiv( { class: "gsuiWindow-handler", "data-dir": "n" } ),
		GSUcreateDiv( { class: "gsuiWindow-handler", "data-dir": "e" } ),
		GSUcreateDiv( { class: "gsuiWindow-handler", "data-dir": "s" } ),
		GSUcreateDiv( { class: "gsuiWindow-handler", "data-dir": "w" } ),
		GSUcreateDiv( { class: "gsuiWindow-handler", "data-dir": "nw" } ),
		GSUcreateDiv( { class: "gsuiWindow-handler", "data-dir": "ne" } ),
		GSUcreateDiv( { class: "gsuiWindow-handler", "data-dir": "sw" } ),
		GSUcreateDiv( { class: "gsuiWindow-handler", "data-dir": "se" } ),
	),
	GSUcreateDiv( { class: "gsuiWindow-wrap" },
		GSUcreateDiv( { class: "gsuiWindow-head" },
			GSUcreateButton( { class: "gsuiWindow-icon gsuiIcon", tabindex: -1 } ),
			GSUcreateDiv( { class: "gsuiWindow-name" } ),
			GSUcreateDiv( { class: "gsuiWindow-headContent" } ),
			GSUcreateDiv( { class: "gsuiWindow-headBtns" },
				GSUcreateButton( { class: "gsuiWindow-headBtn gsuiIcon", "data-action": "minimize", "data-icon": "minimize", title: "Minimize" } ),
				GSUcreateButton( { class: "gsuiWindow-headBtn", "data-action": "restore", title: "Restore" },
					GSUcreateI( { class: "gsuiIcon", "data-icon": "restore", inert: true } ),
					GSUcreateI( { class: "gsuiIcon", "data-icon": "compress", inert: true } ),
				),
				GSUcreateButton( { class: "gsuiWindow-headBtn", "data-action": "maximize", title: "Maximize" },
					GSUcreateI( { class: "gsuiIcon", "data-icon": "maximize", inert: true } ),
					GSUcreateI( { class: "gsuiIcon", "data-icon": "expand", inert: true } ),
				),
				GSUcreateButton( { class: "gsuiWindow-headBtn gsuiIcon", "data-action": "close", "data-icon": "close", title: "Close" } ),
			),
		),
		GSUcreateDiv( { class: "gsuiWindow-content" } ),
	),
] );
